//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniToLua
{
    using SoftwareRenderer;
    using SoftwareRenderer.Scene;
    using SoftwareRenderer.Render;
    using SoftwareRenderer.Core;
    using SoftwareRenderer.Component;
    using Common;
    
    
    public class LuaBinder
    {
        
        public static void Bind(UniLua.LuaState L)
        {
			L.BeginModule(null);
			L.BeginModule("Common");
			Common1LogWrap.Register(L);
			L.EndModule();
			L.BeginModule("SoftwareRenderer");
			L.BeginModule("Component");
			SoftwareRenderer1Component1LuaObjectWrap.Register(L);
			SoftwareRenderer1Component1CubeRendererWrap.Register(L);
			L.EndModule();
			L.BeginModule("Render");
			SoftwareRenderer1Render1BaseFragmentInWrap.Register(L);
			SoftwareRenderer1Render1MeshWrap.Register(L);
			SoftwareRenderer1Render1MeshRendererWrap.Register(L);
			SoftwareRenderer1Render1DrawCommandWrap.Register(L);
			SoftwareRenderer1Render1SoftwareRenderDeviceWrap.Register(L);
			SoftwareRenderer1Render1RenderModeWrap.Register(L);
			SoftwareRenderer1Render1CameraWrap.Register(L);
			SoftwareRenderer1Render1VertexWrap.Register(L);
			SoftwareRenderer1Render1BaseVertexInWrap.Register(L);
			SoftwareRenderer1Render1TextureFilterModeWrap.Register(L);
			SoftwareRenderer1Render1TextureWrap.Register(L);
			SoftwareRenderer1Render1MaterialWrap.Register(L);
			SoftwareRenderer1Render1ShaderWrap.Register(L);
			SoftwareRenderer1Render1RendererWrap.Register(L);
			L.EndModule();
			SoftwareRenderer1ProgramWrap.Register(L);
			L.BeginModule("Scene");
			SoftwareRenderer1Scene1TestWorldWrap.Register(L);
			SoftwareRenderer1Scene1LuaWorldWrap.Register(L);
			L.EndModule();
			L.BeginModule("Core");
			SoftwareRenderer1Core1LuaManagerWrap.Register(L);
			SoftwareRenderer1Core1TransformWrap.Register(L);
			SoftwareRenderer1Core1InputSystemWrap.Register(L);
			SoftwareRenderer1Core1SDLRendererWrap.Register(L);
			SoftwareRenderer1Core1WorldObjectWrap.Register(L);
			SoftwareRenderer1Core1BehaviorWrap.Register(L);
			SoftwareRenderer1Core1WorldWrap.Register(L);
			SoftwareRenderer1Core1ApplicationWrap.Register(L);
			L.EndModule();
			L.EndModule();
			L.EndModule();
        }
    }
}
