//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniToLua
{
    using SDL2;
    
    
    public class SDL21SDL1SDL_MessageBoxButtonFlagsWrap
    {
        
        public static void Register(UniLua.ILuaState L)
        {
			L.BeginEnum(typeof(SDL2.SDL.SDL_MessageBoxButtonFlags));
			L.RegVar("SDL_MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT", get_SDL_MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT, null);
			L.RegVar("SDL_MESSAGEBOX_BUTTON_ESCAPEKEY_DEFAULT", get_SDL_MESSAGEBOX_BUTTON_ESCAPEKEY_DEFAULT, null);
			L.EndEnum();
        }
        
        private static int get_SDL_MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_MessageBoxButtonFlags.SDL_MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT);
			return 1;
        }
        
        private static int get_SDL_MESSAGEBOX_BUTTON_ESCAPEKEY_DEFAULT(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_MessageBoxButtonFlags.SDL_MESSAGEBOX_BUTTON_ESCAPEKEY_DEFAULT);
			return 1;
        }
    }
}
