//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniToLua
{
    using SDL2;
    
    
    public class SDL21SDL_image1IMG_InitFlagsWrap
    {
        
        public static void Register(UniLua.ILuaState L)
        {
			L.BeginEnum(typeof(SDL2.SDL_image.IMG_InitFlags));
			L.RegVar("IMG_INIT_JPG", get_IMG_INIT_JPG, null);
			L.RegVar("IMG_INIT_PNG", get_IMG_INIT_PNG, null);
			L.RegVar("IMG_INIT_TIF", get_IMG_INIT_TIF, null);
			L.RegVar("IMG_INIT_WEBP", get_IMG_INIT_WEBP, null);
			L.EndEnum();
        }
        
        private static int get_IMG_INIT_JPG(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL_image.IMG_InitFlags.IMG_INIT_JPG);
			return 1;
        }
        
        private static int get_IMG_INIT_PNG(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL_image.IMG_InitFlags.IMG_INIT_PNG);
			return 1;
        }
        
        private static int get_IMG_INIT_TIF(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL_image.IMG_InitFlags.IMG_INIT_TIF);
			return 1;
        }
        
        private static int get_IMG_INIT_WEBP(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL_image.IMG_InitFlags.IMG_INIT_WEBP);
			return 1;
        }
    }
}
