//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniToLua
{
    using SDL2;
    using System;
    
    
    public class SDL21SDL_imageWrap
    {
        
        public static void Register(UniLua.ILuaState L)
        {
			L.BeginStaticLib("SDL_image");
			L.RegVar("SDL_IMAGE_MAJOR_VERSION", get_SDL_IMAGE_MAJOR_VERSION, null);
			L.RegVar("SDL_IMAGE_MINOR_VERSION", get_SDL_IMAGE_MINOR_VERSION, null);
			L.RegVar("SDL_IMAGE_PATCHLEVEL", get_SDL_IMAGE_PATCHLEVEL, null);
			L.RegFunction("IMG_Linked_Version", IMG_Linked_Version);
			L.RegFunction("IMG_Init", IMG_Init);
			L.RegFunction("IMG_Quit", IMG_Quit);
			L.RegFunction("IMG_Load", IMG_Load);
			L.RegFunction("IMG_Load_RW", IMG_Load_RW);
			L.RegFunction("IMG_LoadTyped_RW", IMG_LoadTyped_RW);
			L.RegFunction("IMG_LoadTexture", IMG_LoadTexture);
			L.RegFunction("IMG_LoadTexture_RW", IMG_LoadTexture_RW);
			L.RegFunction("IMG_LoadTextureTyped_RW", IMG_LoadTextureTyped_RW);
			L.RegFunction("IMG_ReadXPMFromArray", IMG_ReadXPMFromArray);
			L.RegFunction("IMG_SavePNG", IMG_SavePNG);
			L.RegFunction("IMG_SavePNG_RW", IMG_SavePNG_RW);
			L.RegFunction("IMG_SaveJPG", IMG_SaveJPG);
			L.RegFunction("IMG_SaveJPG_RW", IMG_SaveJPG_RW);
			L.RegFunction("IMG_GetError", IMG_GetError);
			L.RegFunction("IMG_SetError", IMG_SetError);
			L.RegFunction("IMG_LoadAnimation", IMG_LoadAnimation);
			L.RegFunction("IMG_LoadAnimation_RW", IMG_LoadAnimation_RW);
			L.RegFunction("IMG_LoadAnimationTyped_RW", IMG_LoadAnimationTyped_RW);
			L.RegFunction("IMG_FreeAnimation", IMG_FreeAnimation);
			L.RegFunction("IMG_LoadGIFAnimation_RW", IMG_LoadGIFAnimation_RW);
			L.EndStaticLib();
        }
        
        private static int get_SDL_IMAGE_MAJOR_VERSION(UniLua.ILuaState L)
        {
			L.PushAny<int>(SDL2.SDL_image.SDL_IMAGE_MAJOR_VERSION);
			return 1;
        }
        
        private static int get_SDL_IMAGE_MINOR_VERSION(UniLua.ILuaState L)
        {
			L.PushAny<int>(SDL2.SDL_image.SDL_IMAGE_MINOR_VERSION);
			return 1;
        }
        
        private static int get_SDL_IMAGE_PATCHLEVEL(UniLua.ILuaState L)
        {
			L.PushAny<int>(SDL2.SDL_image.SDL_IMAGE_PATCHLEVEL);
			return 1;
        }
        
        private static int IMG_Linked_Version(UniLua.ILuaState L)
        {
			if(L.CheckNum(0))
			{
				SDL2.SDL.SDL_version result;
				result = SDL2.SDL_image.IMG_Linked_Version();
				L.PushAny<SDL2.SDL.SDL_version>(result);
				return 1;
			}
			L.L_Error("call function IMG_Linked_Version args is error");
			return 1;
        }
        
        private static int IMG_Init(UniLua.ILuaState L)
        {
			if(L.CheckNum(1) && L.CheckType<SDL2.SDL_image.IMG_InitFlags>(1))
			{
				int result;
				var arg1 = L.CheckAny<SDL2.SDL_image.IMG_InitFlags>(1);
				result = SDL2.SDL_image.IMG_Init(arg1);
				L.PushAny<int>(result);
				return 1;
			}
			L.L_Error("call function IMG_Init args is error");
			return 1;
        }
        
        private static int IMG_Quit(UniLua.ILuaState L)
        {
			if(L.CheckNum(0))
			{
				SDL2.SDL_image.IMG_Quit();
				return 0;
			}
			L.L_Error("call function IMG_Quit args is error");
			return 1;
        }
        
        private static int IMG_Load(UniLua.ILuaState L)
        {
			if(L.CheckNum(1) && L.CheckType<string>(1))
			{
				System.IntPtr result;
				var arg1 = L.CheckAny<string>(1);
				result = SDL2.SDL_image.IMG_Load(arg1);
				L.PushAny<System.IntPtr>(result);
				return 1;
			}
			L.L_Error("call function IMG_Load args is error");
			return 1;
        }
        
        private static int IMG_Load_RW(UniLua.ILuaState L)
        {
			if(L.CheckNum(2) && L.CheckType<System.IntPtr, int>(1))
			{
				System.IntPtr result;
				var arg1 = L.CheckAny<System.IntPtr>(1);
				var arg2 = L.CheckAny<int>(2);
				result = SDL2.SDL_image.IMG_Load_RW(arg1, arg2);
				L.PushAny<System.IntPtr>(result);
				return 1;
			}
			L.L_Error("call function IMG_Load_RW args is error");
			return 1;
        }
        
        private static int IMG_LoadTyped_RW(UniLua.ILuaState L)
        {
			if(L.CheckNum(3) && L.CheckType<System.IntPtr, int, string>(1))
			{
				System.IntPtr result;
				var arg1 = L.CheckAny<System.IntPtr>(1);
				var arg2 = L.CheckAny<int>(2);
				var arg3 = L.CheckAny<string>(3);
				result = SDL2.SDL_image.IMG_LoadTyped_RW(arg1, arg2, arg3);
				L.PushAny<System.IntPtr>(result);
				return 1;
			}
			L.L_Error("call function IMG_LoadTyped_RW args is error");
			return 1;
        }
        
        private static int IMG_LoadTexture(UniLua.ILuaState L)
        {
			if(L.CheckNum(2) && L.CheckType<System.IntPtr, string>(1))
			{
				System.IntPtr result;
				var arg1 = L.CheckAny<System.IntPtr>(1);
				var arg2 = L.CheckAny<string>(2);
				result = SDL2.SDL_image.IMG_LoadTexture(arg1, arg2);
				L.PushAny<System.IntPtr>(result);
				return 1;
			}
			L.L_Error("call function IMG_LoadTexture args is error");
			return 1;
        }
        
        private static int IMG_LoadTexture_RW(UniLua.ILuaState L)
        {
			if(L.CheckNum(3) && L.CheckType<System.IntPtr, System.IntPtr, int>(1))
			{
				System.IntPtr result;
				var arg1 = L.CheckAny<System.IntPtr>(1);
				var arg2 = L.CheckAny<System.IntPtr>(2);
				var arg3 = L.CheckAny<int>(3);
				result = SDL2.SDL_image.IMG_LoadTexture_RW(arg1, arg2, arg3);
				L.PushAny<System.IntPtr>(result);
				return 1;
			}
			L.L_Error("call function IMG_LoadTexture_RW args is error");
			return 1;
        }
        
        private static int IMG_LoadTextureTyped_RW(UniLua.ILuaState L)
        {
			if(L.CheckNum(4) && L.CheckType<System.IntPtr, System.IntPtr, int, string>(1))
			{
				System.IntPtr result;
				var arg1 = L.CheckAny<System.IntPtr>(1);
				var arg2 = L.CheckAny<System.IntPtr>(2);
				var arg3 = L.CheckAny<int>(3);
				var arg4 = L.CheckAny<string>(4);
				result = SDL2.SDL_image.IMG_LoadTextureTyped_RW(arg1, arg2, arg3, arg4);
				L.PushAny<System.IntPtr>(result);
				return 1;
			}
			L.L_Error("call function IMG_LoadTextureTyped_RW args is error");
			return 1;
        }
        
        private static int IMG_ReadXPMFromArray(UniLua.ILuaState L)
        {
			if(L.CheckNum(1) && L.CheckType<string[]>(1))
			{
				System.IntPtr result;
				var arg1 = L.CheckAny<string[]>(1);
				result = SDL2.SDL_image.IMG_ReadXPMFromArray(arg1);
				L.PushAny<System.IntPtr>(result);
				return 1;
			}
			L.L_Error("call function IMG_ReadXPMFromArray args is error");
			return 1;
        }
        
        private static int IMG_SavePNG(UniLua.ILuaState L)
        {
			if(L.CheckNum(2) && L.CheckType<System.IntPtr, string>(1))
			{
				int result;
				var arg1 = L.CheckAny<System.IntPtr>(1);
				var arg2 = L.CheckAny<string>(2);
				result = SDL2.SDL_image.IMG_SavePNG(arg1, arg2);
				L.PushAny<int>(result);
				return 1;
			}
			L.L_Error("call function IMG_SavePNG args is error");
			return 1;
        }
        
        private static int IMG_SavePNG_RW(UniLua.ILuaState L)
        {
			if(L.CheckNum(3) && L.CheckType<System.IntPtr, System.IntPtr, int>(1))
			{
				int result;
				var arg1 = L.CheckAny<System.IntPtr>(1);
				var arg2 = L.CheckAny<System.IntPtr>(2);
				var arg3 = L.CheckAny<int>(3);
				result = SDL2.SDL_image.IMG_SavePNG_RW(arg1, arg2, arg3);
				L.PushAny<int>(result);
				return 1;
			}
			L.L_Error("call function IMG_SavePNG_RW args is error");
			return 1;
        }
        
        private static int IMG_SaveJPG(UniLua.ILuaState L)
        {
			if(L.CheckNum(3) && L.CheckType<System.IntPtr, string, int>(1))
			{
				int result;
				var arg1 = L.CheckAny<System.IntPtr>(1);
				var arg2 = L.CheckAny<string>(2);
				var arg3 = L.CheckAny<int>(3);
				result = SDL2.SDL_image.IMG_SaveJPG(arg1, arg2, arg3);
				L.PushAny<int>(result);
				return 1;
			}
			L.L_Error("call function IMG_SaveJPG args is error");
			return 1;
        }
        
        private static int IMG_SaveJPG_RW(UniLua.ILuaState L)
        {
			if(L.CheckNum(4) && L.CheckType<System.IntPtr, System.IntPtr, int, int>(1))
			{
				int result;
				var arg1 = L.CheckAny<System.IntPtr>(1);
				var arg2 = L.CheckAny<System.IntPtr>(2);
				var arg3 = L.CheckAny<int>(3);
				var arg4 = L.CheckAny<int>(4);
				result = SDL2.SDL_image.IMG_SaveJPG_RW(arg1, arg2, arg3, arg4);
				L.PushAny<int>(result);
				return 1;
			}
			L.L_Error("call function IMG_SaveJPG_RW args is error");
			return 1;
        }
        
        private static int IMG_GetError(UniLua.ILuaState L)
        {
			if(L.CheckNum(0))
			{
				string result;
				result = SDL2.SDL_image.IMG_GetError();
				L.PushAny<string>(result);
				return 1;
			}
			L.L_Error("call function IMG_GetError args is error");
			return 1;
        }
        
        private static int IMG_SetError(UniLua.ILuaState L)
        {
			if(L.CheckNum(1) && L.CheckType<string>(1))
			{
				var arg1 = L.CheckAny<string>(1);
				SDL2.SDL_image.IMG_SetError(arg1);
				return 0;
			}
			L.L_Error("call function IMG_SetError args is error");
			return 1;
        }
        
        private static int IMG_LoadAnimation(UniLua.ILuaState L)
        {
			if(L.CheckNum(1) && L.CheckType<string>(1))
			{
				System.IntPtr result;
				var arg1 = L.CheckAny<string>(1);
				result = SDL2.SDL_image.IMG_LoadAnimation(arg1);
				L.PushAny<System.IntPtr>(result);
				return 1;
			}
			L.L_Error("call function IMG_LoadAnimation args is error");
			return 1;
        }
        
        private static int IMG_LoadAnimation_RW(UniLua.ILuaState L)
        {
			if(L.CheckNum(2) && L.CheckType<System.IntPtr, int>(1))
			{
				System.IntPtr result;
				var arg1 = L.CheckAny<System.IntPtr>(1);
				var arg2 = L.CheckAny<int>(2);
				result = SDL2.SDL_image.IMG_LoadAnimation_RW(arg1, arg2);
				L.PushAny<System.IntPtr>(result);
				return 1;
			}
			L.L_Error("call function IMG_LoadAnimation_RW args is error");
			return 1;
        }
        
        private static int IMG_LoadAnimationTyped_RW(UniLua.ILuaState L)
        {
			if(L.CheckNum(3) && L.CheckType<System.IntPtr, int, string>(1))
			{
				System.IntPtr result;
				var arg1 = L.CheckAny<System.IntPtr>(1);
				var arg2 = L.CheckAny<int>(2);
				var arg3 = L.CheckAny<string>(3);
				result = SDL2.SDL_image.IMG_LoadAnimationTyped_RW(arg1, arg2, arg3);
				L.PushAny<System.IntPtr>(result);
				return 1;
			}
			L.L_Error("call function IMG_LoadAnimationTyped_RW args is error");
			return 1;
        }
        
        private static int IMG_FreeAnimation(UniLua.ILuaState L)
        {
			if(L.CheckNum(1) && L.CheckType<System.IntPtr>(1))
			{
				var arg1 = L.CheckAny<System.IntPtr>(1);
				SDL2.SDL_image.IMG_FreeAnimation(arg1);
				return 0;
			}
			L.L_Error("call function IMG_FreeAnimation args is error");
			return 1;
        }
        
        private static int IMG_LoadGIFAnimation_RW(UniLua.ILuaState L)
        {
			if(L.CheckNum(1) && L.CheckType<System.IntPtr>(1))
			{
				System.IntPtr result;
				var arg1 = L.CheckAny<System.IntPtr>(1);
				result = SDL2.SDL_image.IMG_LoadGIFAnimation_RW(arg1);
				L.PushAny<System.IntPtr>(result);
				return 1;
			}
			L.L_Error("call function IMG_LoadGIFAnimation_RW args is error");
			return 1;
        }
    }
}
