//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniToLua
{
    using SDL2;
    using System;
    
    
    public class SDL21SDL1SDL_versionWrap
    {
        
        public static void Register(UniLua.ILuaState L)
        {
			L.BeginClass(typeof(SDL2.SDL.SDL_version), typeof(System.ValueType));
			L.RegFunction("New", _CreateSDL21SDL1SDL_version);
			L.RegVar("major", get_major, set_major);
			L.RegVar("minor", get_minor, set_minor);
			L.RegVar("patch", get_patch, set_patch);
			L.RegFunction("Equals", Equals);
			L.RegFunction("GetHashCode", GetHashCode);
			L.RegFunction("ToString", ToString);
			L.RegFunction("GetType", GetType);
			L.EndClass();
        }
        
        private static int _CreateSDL21SDL1SDL_version(UniLua.ILuaState L)
        {
			if(L.CheckNum(0)) {
				L.PushAny<SDL2.SDL.SDL_version>(default(SDL2.SDL.SDL_version));
				return 1;
			}
			L.L_Error("call SDL_version constructor args is error");
			return 1;
        }
        
        private static int get_major(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.SDL_version) L.ToUserData(1);
			L.PushAny<byte>(obj.major);
			return 1;
        }
        
        private static int set_major(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.SDL_version) L.ToUserData(1);
			var value = L.CheckAny<byte>(2);
			obj.major = value;
			// replace old struct
			L.PushAny<SDL2.SDL.SDL_version>(obj);
			L.Replace(1);
			return 0;
        }
        
        private static int get_minor(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.SDL_version) L.ToUserData(1);
			L.PushAny<byte>(obj.minor);
			return 1;
        }
        
        private static int set_minor(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.SDL_version) L.ToUserData(1);
			var value = L.CheckAny<byte>(2);
			obj.minor = value;
			// replace old struct
			L.PushAny<SDL2.SDL.SDL_version>(obj);
			L.Replace(1);
			return 0;
        }
        
        private static int get_patch(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.SDL_version) L.ToUserData(1);
			L.PushAny<byte>(obj.patch);
			return 1;
        }
        
        private static int set_patch(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.SDL_version) L.ToUserData(1);
			var value = L.CheckAny<byte>(2);
			obj.patch = value;
			// replace old struct
			L.PushAny<SDL2.SDL.SDL_version>(obj);
			L.Replace(1);
			return 0;
        }
        
        private static int Equals(UniLua.ILuaState L)
        {
			if(L.CheckNum(2) && L.CheckType<SDL2.SDL.SDL_version, object>(1))
			{
				bool result;
				var obj = (SDL2.SDL.SDL_version) L.ToUserData(1);
				var arg1 = L.CheckAny<object>(2);
				result = obj.Equals(arg1);
				L.PushAny<bool>(result);
				return 1;
			}
			L.L_Error("call function Equals args is error");
			return 1;
        }
        
        private static int GetHashCode(UniLua.ILuaState L)
        {
			if(L.CheckNum(1))
			{
				int result;
				var obj = (SDL2.SDL.SDL_version) L.ToUserData(1);
				result = obj.GetHashCode();
				L.PushAny<int>(result);
				return 1;
			}
			L.L_Error("call function GetHashCode args is error");
			return 1;
        }
        
        private static int ToString(UniLua.ILuaState L)
        {
			if(L.CheckNum(1))
			{
				string result;
				var obj = (SDL2.SDL.SDL_version) L.ToUserData(1);
				result = obj.ToString();
				L.PushAny<string>(result);
				return 1;
			}
			L.L_Error("call function ToString args is error");
			return 1;
        }
        
        private static int GetType(UniLua.ILuaState L)
        {
			if(L.CheckNum(1))
			{
				System.Type result;
				var obj = (SDL2.SDL.SDL_version) L.ToUserData(1);
				result = obj.GetType();
				L.PushAny<System.Type>(result);
				return 1;
			}
			L.L_Error("call function GetType args is error");
			return 1;
        }
    }
}
