//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniToLua
{
    using SDL2;
    
    
    public class SDL21SDL1SDL_boolWrap
    {
        
        public static void Register(UniLua.ILuaState L)
        {
			L.BeginEnum(typeof(SDL2.SDL.SDL_bool));
			L.RegVar("SDL_FALSE", get_SDL_FALSE, null);
			L.RegVar("SDL_TRUE", get_SDL_TRUE, null);
			L.EndEnum();
        }
        
        private static int get_SDL_FALSE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_bool.SDL_FALSE);
			return 1;
        }
        
        private static int get_SDL_TRUE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_bool.SDL_TRUE);
			return 1;
        }
    }
}
