//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniToLua
{
    using SDL2;
    
    
    public class SDL21SDL1SDL_SYSWM_TYPEWrap
    {
        
        public static void Register(UniLua.ILuaState L)
        {
			L.BeginEnum(typeof(SDL2.SDL.SDL_SYSWM_TYPE));
			L.RegVar("SDL_SYSWM_UNKNOWN", get_SDL_SYSWM_UNKNOWN, null);
			L.RegVar("SDL_SYSWM_WINDOWS", get_SDL_SYSWM_WINDOWS, null);
			L.RegVar("SDL_SYSWM_X11", get_SDL_SYSWM_X11, null);
			L.RegVar("SDL_SYSWM_DIRECTFB", get_SDL_SYSWM_DIRECTFB, null);
			L.RegVar("SDL_SYSWM_COCOA", get_SDL_SYSWM_COCOA, null);
			L.RegVar("SDL_SYSWM_UIKIT", get_SDL_SYSWM_UIKIT, null);
			L.RegVar("SDL_SYSWM_WAYLAND", get_SDL_SYSWM_WAYLAND, null);
			L.RegVar("SDL_SYSWM_MIR", get_SDL_SYSWM_MIR, null);
			L.RegVar("SDL_SYSWM_WINRT", get_SDL_SYSWM_WINRT, null);
			L.RegVar("SDL_SYSWM_ANDROID", get_SDL_SYSWM_ANDROID, null);
			L.RegVar("SDL_SYSWM_VIVANTE", get_SDL_SYSWM_VIVANTE, null);
			L.RegVar("SDL_SYSWM_OS2", get_SDL_SYSWM_OS2, null);
			L.RegVar("SDL_SYSWM_HAIKU", get_SDL_SYSWM_HAIKU, null);
			L.EndEnum();
        }
        
        private static int get_SDL_SYSWM_UNKNOWN(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_SYSWM_TYPE.SDL_SYSWM_UNKNOWN);
			return 1;
        }
        
        private static int get_SDL_SYSWM_WINDOWS(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_SYSWM_TYPE.SDL_SYSWM_WINDOWS);
			return 1;
        }
        
        private static int get_SDL_SYSWM_X11(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_SYSWM_TYPE.SDL_SYSWM_X11);
			return 1;
        }
        
        private static int get_SDL_SYSWM_DIRECTFB(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_SYSWM_TYPE.SDL_SYSWM_DIRECTFB);
			return 1;
        }
        
        private static int get_SDL_SYSWM_COCOA(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_SYSWM_TYPE.SDL_SYSWM_COCOA);
			return 1;
        }
        
        private static int get_SDL_SYSWM_UIKIT(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_SYSWM_TYPE.SDL_SYSWM_UIKIT);
			return 1;
        }
        
        private static int get_SDL_SYSWM_WAYLAND(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_SYSWM_TYPE.SDL_SYSWM_WAYLAND);
			return 1;
        }
        
        private static int get_SDL_SYSWM_MIR(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_SYSWM_TYPE.SDL_SYSWM_MIR);
			return 1;
        }
        
        private static int get_SDL_SYSWM_WINRT(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_SYSWM_TYPE.SDL_SYSWM_WINRT);
			return 1;
        }
        
        private static int get_SDL_SYSWM_ANDROID(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_SYSWM_TYPE.SDL_SYSWM_ANDROID);
			return 1;
        }
        
        private static int get_SDL_SYSWM_VIVANTE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_SYSWM_TYPE.SDL_SYSWM_VIVANTE);
			return 1;
        }
        
        private static int get_SDL_SYSWM_OS2(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_SYSWM_TYPE.SDL_SYSWM_OS2);
			return 1;
        }
        
        private static int get_SDL_SYSWM_HAIKU(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_SYSWM_TYPE.SDL_SYSWM_HAIKU);
			return 1;
        }
    }
}
