//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniToLua
{
    using SDL2;
    
    
    public class SDL21SDL1SDL_HintPriorityWrap
    {
        
        public static void Register(UniLua.ILuaState L)
        {
			L.BeginEnum(typeof(SDL2.SDL.SDL_HintPriority));
			L.RegVar("SDL_HINT_DEFAULT", get_SDL_HINT_DEFAULT, null);
			L.RegVar("SDL_HINT_NORMAL", get_SDL_HINT_NORMAL, null);
			L.RegVar("SDL_HINT_OVERRIDE", get_SDL_HINT_OVERRIDE, null);
			L.EndEnum();
        }
        
        private static int get_SDL_HINT_DEFAULT(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_HintPriority.SDL_HINT_DEFAULT);
			return 1;
        }
        
        private static int get_SDL_HINT_NORMAL(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_HintPriority.SDL_HINT_NORMAL);
			return 1;
        }
        
        private static int get_SDL_HINT_OVERRIDE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_HintPriority.SDL_HINT_OVERRIDE);
			return 1;
        }
    }
}
