//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniToLua
{
    using SDL2;
    
    
    public class SDL21SDL1SDL_LogCategoryWrap
    {
        
        public static void Register(UniLua.ILuaState L)
        {
			L.BeginEnum(typeof(SDL2.SDL.SDL_LogCategory));
			L.RegVar("SDL_LOG_CATEGORY_APPLICATION", get_SDL_LOG_CATEGORY_APPLICATION, null);
			L.RegVar("SDL_LOG_CATEGORY_ERROR", get_SDL_LOG_CATEGORY_ERROR, null);
			L.RegVar("SDL_LOG_CATEGORY_ASSERT", get_SDL_LOG_CATEGORY_ASSERT, null);
			L.RegVar("SDL_LOG_CATEGORY_SYSTEM", get_SDL_LOG_CATEGORY_SYSTEM, null);
			L.RegVar("SDL_LOG_CATEGORY_AUDIO", get_SDL_LOG_CATEGORY_AUDIO, null);
			L.RegVar("SDL_LOG_CATEGORY_VIDEO", get_SDL_LOG_CATEGORY_VIDEO, null);
			L.RegVar("SDL_LOG_CATEGORY_RENDER", get_SDL_LOG_CATEGORY_RENDER, null);
			L.RegVar("SDL_LOG_CATEGORY_INPUT", get_SDL_LOG_CATEGORY_INPUT, null);
			L.RegVar("SDL_LOG_CATEGORY_TEST", get_SDL_LOG_CATEGORY_TEST, null);
			L.RegVar("SDL_LOG_CATEGORY_RESERVED1", get_SDL_LOG_CATEGORY_RESERVED1, null);
			L.RegVar("SDL_LOG_CATEGORY_RESERVED2", get_SDL_LOG_CATEGORY_RESERVED2, null);
			L.RegVar("SDL_LOG_CATEGORY_RESERVED3", get_SDL_LOG_CATEGORY_RESERVED3, null);
			L.RegVar("SDL_LOG_CATEGORY_RESERVED4", get_SDL_LOG_CATEGORY_RESERVED4, null);
			L.RegVar("SDL_LOG_CATEGORY_RESERVED5", get_SDL_LOG_CATEGORY_RESERVED5, null);
			L.RegVar("SDL_LOG_CATEGORY_RESERVED6", get_SDL_LOG_CATEGORY_RESERVED6, null);
			L.RegVar("SDL_LOG_CATEGORY_RESERVED7", get_SDL_LOG_CATEGORY_RESERVED7, null);
			L.RegVar("SDL_LOG_CATEGORY_RESERVED8", get_SDL_LOG_CATEGORY_RESERVED8, null);
			L.RegVar("SDL_LOG_CATEGORY_RESERVED9", get_SDL_LOG_CATEGORY_RESERVED9, null);
			L.RegVar("SDL_LOG_CATEGORY_RESERVED10", get_SDL_LOG_CATEGORY_RESERVED10, null);
			L.RegVar("SDL_LOG_CATEGORY_CUSTOM", get_SDL_LOG_CATEGORY_CUSTOM, null);
			L.EndEnum();
        }
        
        private static int get_SDL_LOG_CATEGORY_APPLICATION(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_LogCategory.SDL_LOG_CATEGORY_APPLICATION);
			return 1;
        }
        
        private static int get_SDL_LOG_CATEGORY_ERROR(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_LogCategory.SDL_LOG_CATEGORY_ERROR);
			return 1;
        }
        
        private static int get_SDL_LOG_CATEGORY_ASSERT(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_LogCategory.SDL_LOG_CATEGORY_ASSERT);
			return 1;
        }
        
        private static int get_SDL_LOG_CATEGORY_SYSTEM(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_LogCategory.SDL_LOG_CATEGORY_SYSTEM);
			return 1;
        }
        
        private static int get_SDL_LOG_CATEGORY_AUDIO(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_LogCategory.SDL_LOG_CATEGORY_AUDIO);
			return 1;
        }
        
        private static int get_SDL_LOG_CATEGORY_VIDEO(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_LogCategory.SDL_LOG_CATEGORY_VIDEO);
			return 1;
        }
        
        private static int get_SDL_LOG_CATEGORY_RENDER(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_LogCategory.SDL_LOG_CATEGORY_RENDER);
			return 1;
        }
        
        private static int get_SDL_LOG_CATEGORY_INPUT(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_LogCategory.SDL_LOG_CATEGORY_INPUT);
			return 1;
        }
        
        private static int get_SDL_LOG_CATEGORY_TEST(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_LogCategory.SDL_LOG_CATEGORY_TEST);
			return 1;
        }
        
        private static int get_SDL_LOG_CATEGORY_RESERVED1(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_LogCategory.SDL_LOG_CATEGORY_RESERVED1);
			return 1;
        }
        
        private static int get_SDL_LOG_CATEGORY_RESERVED2(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_LogCategory.SDL_LOG_CATEGORY_RESERVED2);
			return 1;
        }
        
        private static int get_SDL_LOG_CATEGORY_RESERVED3(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_LogCategory.SDL_LOG_CATEGORY_RESERVED3);
			return 1;
        }
        
        private static int get_SDL_LOG_CATEGORY_RESERVED4(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_LogCategory.SDL_LOG_CATEGORY_RESERVED4);
			return 1;
        }
        
        private static int get_SDL_LOG_CATEGORY_RESERVED5(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_LogCategory.SDL_LOG_CATEGORY_RESERVED5);
			return 1;
        }
        
        private static int get_SDL_LOG_CATEGORY_RESERVED6(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_LogCategory.SDL_LOG_CATEGORY_RESERVED6);
			return 1;
        }
        
        private static int get_SDL_LOG_CATEGORY_RESERVED7(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_LogCategory.SDL_LOG_CATEGORY_RESERVED7);
			return 1;
        }
        
        private static int get_SDL_LOG_CATEGORY_RESERVED8(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_LogCategory.SDL_LOG_CATEGORY_RESERVED8);
			return 1;
        }
        
        private static int get_SDL_LOG_CATEGORY_RESERVED9(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_LogCategory.SDL_LOG_CATEGORY_RESERVED9);
			return 1;
        }
        
        private static int get_SDL_LOG_CATEGORY_RESERVED10(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_LogCategory.SDL_LOG_CATEGORY_RESERVED10);
			return 1;
        }
        
        private static int get_SDL_LOG_CATEGORY_CUSTOM(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_LogCategory.SDL_LOG_CATEGORY_CUSTOM);
			return 1;
        }
    }
}
