//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniToLua
{
    using SDL2;
    using System;
    
    
    public class SDL21SDL1SDL_RendererInfoWrap
    {
        
        public static void Register(UniLua.ILuaState L)
        {
			L.BeginClass(typeof(SDL2.SDL.SDL_RendererInfo), typeof(System.ValueType));
			L.RegFunction("New", _CreateSDL21SDL1SDL_RendererInfo);
			L.RegVar("name", get_name, set_name);
			L.RegVar("flags", get_flags, set_flags);
			L.RegVar("num_texture_formats", get_num_texture_formats, set_num_texture_formats);
			L.RegVar("max_texture_width", get_max_texture_width, set_max_texture_width);
			L.RegVar("max_texture_height", get_max_texture_height, set_max_texture_height);
			L.RegFunction("Equals", Equals);
			L.RegFunction("GetHashCode", GetHashCode);
			L.RegFunction("ToString", ToString);
			L.RegFunction("GetType", GetType);
			L.EndClass();
        }
        
        private static int _CreateSDL21SDL1SDL_RendererInfo(UniLua.ILuaState L)
        {
			if(L.CheckNum(0)) {
				L.PushAny<SDL2.SDL.SDL_RendererInfo>(default(SDL2.SDL.SDL_RendererInfo));
				return 1;
			}
			L.L_Error("call SDL_RendererInfo constructor args is error");
			return 1;
        }
        
        private static int get_name(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.SDL_RendererInfo) L.ToUserData(1);
			L.PushAny<System.IntPtr>(obj.name);
			return 1;
        }
        
        private static int set_name(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.SDL_RendererInfo) L.ToUserData(1);
			var value = L.CheckAny<System.IntPtr>(2);
			obj.name = value;
			// replace old struct
			L.PushAny<SDL2.SDL.SDL_RendererInfo>(obj);
			L.Replace(1);
			return 0;
        }
        
        private static int get_flags(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.SDL_RendererInfo) L.ToUserData(1);
			L.PushAny<uint>(obj.flags);
			return 1;
        }
        
        private static int set_flags(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.SDL_RendererInfo) L.ToUserData(1);
			var value = L.CheckAny<uint>(2);
			obj.flags = value;
			// replace old struct
			L.PushAny<SDL2.SDL.SDL_RendererInfo>(obj);
			L.Replace(1);
			return 0;
        }
        
        private static int get_num_texture_formats(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.SDL_RendererInfo) L.ToUserData(1);
			L.PushAny<uint>(obj.num_texture_formats);
			return 1;
        }
        
        private static int set_num_texture_formats(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.SDL_RendererInfo) L.ToUserData(1);
			var value = L.CheckAny<uint>(2);
			obj.num_texture_formats = value;
			// replace old struct
			L.PushAny<SDL2.SDL.SDL_RendererInfo>(obj);
			L.Replace(1);
			return 0;
        }
        
        private static int get_max_texture_width(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.SDL_RendererInfo) L.ToUserData(1);
			L.PushAny<int>(obj.max_texture_width);
			return 1;
        }
        
        private static int set_max_texture_width(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.SDL_RendererInfo) L.ToUserData(1);
			var value = L.CheckAny<int>(2);
			obj.max_texture_width = value;
			// replace old struct
			L.PushAny<SDL2.SDL.SDL_RendererInfo>(obj);
			L.Replace(1);
			return 0;
        }
        
        private static int get_max_texture_height(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.SDL_RendererInfo) L.ToUserData(1);
			L.PushAny<int>(obj.max_texture_height);
			return 1;
        }
        
        private static int set_max_texture_height(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.SDL_RendererInfo) L.ToUserData(1);
			var value = L.CheckAny<int>(2);
			obj.max_texture_height = value;
			// replace old struct
			L.PushAny<SDL2.SDL.SDL_RendererInfo>(obj);
			L.Replace(1);
			return 0;
        }
        
        private static int Equals(UniLua.ILuaState L)
        {
			if(L.CheckNum(2) && L.CheckType<SDL2.SDL.SDL_RendererInfo, object>(1))
			{
				bool result;
				var obj = (SDL2.SDL.SDL_RendererInfo) L.ToUserData(1);
				var arg1 = L.CheckAny<object>(2);
				result = obj.Equals(arg1);
				L.PushAny<bool>(result);
				return 1;
			}
			L.L_Error("call function Equals args is error");
			return 1;
        }
        
        private static int GetHashCode(UniLua.ILuaState L)
        {
			if(L.CheckNum(1))
			{
				int result;
				var obj = (SDL2.SDL.SDL_RendererInfo) L.ToUserData(1);
				result = obj.GetHashCode();
				L.PushAny<int>(result);
				return 1;
			}
			L.L_Error("call function GetHashCode args is error");
			return 1;
        }
        
        private static int ToString(UniLua.ILuaState L)
        {
			if(L.CheckNum(1))
			{
				string result;
				var obj = (SDL2.SDL.SDL_RendererInfo) L.ToUserData(1);
				result = obj.ToString();
				L.PushAny<string>(result);
				return 1;
			}
			L.L_Error("call function ToString args is error");
			return 1;
        }
        
        private static int GetType(UniLua.ILuaState L)
        {
			if(L.CheckNum(1))
			{
				System.Type result;
				var obj = (SDL2.SDL.SDL_RendererInfo) L.ToUserData(1);
				result = obj.GetType();
				L.PushAny<System.Type>(result);
				return 1;
			}
			L.L_Error("call function GetType args is error");
			return 1;
        }
    }
}
