//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniToLua
{
    using SDL2;
    
    
    public class SDL21SDL1SDL_PixelTypeWrap
    {
        
        public static void Register(UniLua.ILuaState L)
        {
			L.BeginEnum(typeof(SDL2.SDL.SDL_PixelType));
			L.RegVar("SDL_PIXELTYPE_UNKNOWN", get_SDL_PIXELTYPE_UNKNOWN, null);
			L.RegVar("SDL_PIXELTYPE_INDEX1", get_SDL_PIXELTYPE_INDEX1, null);
			L.RegVar("SDL_PIXELTYPE_INDEX4", get_SDL_PIXELTYPE_INDEX4, null);
			L.RegVar("SDL_PIXELTYPE_INDEX8", get_SDL_PIXELTYPE_INDEX8, null);
			L.RegVar("SDL_PIXELTYPE_PACKED8", get_SDL_PIXELTYPE_PACKED8, null);
			L.RegVar("SDL_PIXELTYPE_PACKED16", get_SDL_PIXELTYPE_PACKED16, null);
			L.RegVar("SDL_PIXELTYPE_PACKED32", get_SDL_PIXELTYPE_PACKED32, null);
			L.RegVar("SDL_PIXELTYPE_ARRAYU8", get_SDL_PIXELTYPE_ARRAYU8, null);
			L.RegVar("SDL_PIXELTYPE_ARRAYU16", get_SDL_PIXELTYPE_ARRAYU16, null);
			L.RegVar("SDL_PIXELTYPE_ARRAYU32", get_SDL_PIXELTYPE_ARRAYU32, null);
			L.RegVar("SDL_PIXELTYPE_ARRAYF16", get_SDL_PIXELTYPE_ARRAYF16, null);
			L.RegVar("SDL_PIXELTYPE_ARRAYF32", get_SDL_PIXELTYPE_ARRAYF32, null);
			L.EndEnum();
        }
        
        private static int get_SDL_PIXELTYPE_UNKNOWN(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_PixelType.SDL_PIXELTYPE_UNKNOWN);
			return 1;
        }
        
        private static int get_SDL_PIXELTYPE_INDEX1(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_PixelType.SDL_PIXELTYPE_INDEX1);
			return 1;
        }
        
        private static int get_SDL_PIXELTYPE_INDEX4(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_PixelType.SDL_PIXELTYPE_INDEX4);
			return 1;
        }
        
        private static int get_SDL_PIXELTYPE_INDEX8(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_PixelType.SDL_PIXELTYPE_INDEX8);
			return 1;
        }
        
        private static int get_SDL_PIXELTYPE_PACKED8(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_PixelType.SDL_PIXELTYPE_PACKED8);
			return 1;
        }
        
        private static int get_SDL_PIXELTYPE_PACKED16(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_PixelType.SDL_PIXELTYPE_PACKED16);
			return 1;
        }
        
        private static int get_SDL_PIXELTYPE_PACKED32(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_PixelType.SDL_PIXELTYPE_PACKED32);
			return 1;
        }
        
        private static int get_SDL_PIXELTYPE_ARRAYU8(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_PixelType.SDL_PIXELTYPE_ARRAYU8);
			return 1;
        }
        
        private static int get_SDL_PIXELTYPE_ARRAYU16(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_PixelType.SDL_PIXELTYPE_ARRAYU16);
			return 1;
        }
        
        private static int get_SDL_PIXELTYPE_ARRAYU32(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_PixelType.SDL_PIXELTYPE_ARRAYU32);
			return 1;
        }
        
        private static int get_SDL_PIXELTYPE_ARRAYF16(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_PixelType.SDL_PIXELTYPE_ARRAYF16);
			return 1;
        }
        
        private static int get_SDL_PIXELTYPE_ARRAYF32(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_PixelType.SDL_PIXELTYPE_ARRAYF32);
			return 1;
        }
    }
}
