//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniToLua
{
    using SDL2;
    
    
    public class SDL21SDL1SDL_RendererFlagsWrap
    {
        
        public static void Register(UniLua.ILuaState L)
        {
			L.BeginEnum(typeof(SDL2.SDL.SDL_RendererFlags));
			L.RegVar("SDL_RENDERER_SOFTWARE", get_SDL_RENDERER_SOFTWARE, null);
			L.RegVar("SDL_RENDERER_ACCELERATED", get_SDL_RENDERER_ACCELERATED, null);
			L.RegVar("SDL_RENDERER_PRESENTVSYNC", get_SDL_RENDERER_PRESENTVSYNC, null);
			L.RegVar("SDL_RENDERER_TARGETTEXTURE", get_SDL_RENDERER_TARGETTEXTURE, null);
			L.EndEnum();
        }
        
        private static int get_SDL_RENDERER_SOFTWARE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_RendererFlags.SDL_RENDERER_SOFTWARE);
			return 1;
        }
        
        private static int get_SDL_RENDERER_ACCELERATED(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_RendererFlags.SDL_RENDERER_ACCELERATED);
			return 1;
        }
        
        private static int get_SDL_RENDERER_PRESENTVSYNC(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_RendererFlags.SDL_RENDERER_PRESENTVSYNC);
			return 1;
        }
        
        private static int get_SDL_RENDERER_TARGETTEXTURE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_RendererFlags.SDL_RENDERER_TARGETTEXTURE);
			return 1;
        }
    }
}
