//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniToLua
{
    using SoftwareRenderer.Render;
    using System;
    using MathLib;
    
    
    public class SoftwareRenderer1Render1DrawCommandWrap
    {
        
        public static void Register(UniLua.ILuaState L)
        {
			L.BeginClass(typeof(SoftwareRenderer.Render.DrawCommand), typeof(System.ValueType));
			L.RegFunction("New", _CreateSoftwareRenderer1Render1DrawCommand);
			L.RegVar("Vertexs", get_Vertexs, set_Vertexs);
			L.RegVar("Indexs", get_Indexs, set_Indexs);
			L.RegVar("Mat", get_Mat, set_Mat);
			L.RegFunction("Equals", Equals);
			L.RegFunction("GetHashCode", GetHashCode);
			L.RegFunction("ToString", ToString);
			L.RegFunction("GetType", GetType);
			L.EndClass();
        }
        
        private static int _CreateSoftwareRenderer1Render1DrawCommand(UniLua.ILuaState L)
        {
			if(L.CheckNum(0)) {
				L.PushAny<SoftwareRenderer.Render.DrawCommand>(default(SoftwareRenderer.Render.DrawCommand));
				return 1;
			}
			L.L_Error("call DrawCommand constructor args is error");
			return 1;
        }
        
        private static int get_Vertexs(UniLua.ILuaState L)
        {
			var obj = (SoftwareRenderer.Render.DrawCommand) L.ToUserData(1);
			L.PushAny<SoftwareRenderer.Render.Vertex[]>(obj.Vertexs);
			return 1;
        }
        
        private static int set_Vertexs(UniLua.ILuaState L)
        {
			var obj = (SoftwareRenderer.Render.DrawCommand) L.ToUserData(1);
			var value = L.CheckAny<SoftwareRenderer.Render.Vertex[]>(2);
			obj.Vertexs = value;
			// replace old struct
			L.PushAny<SoftwareRenderer.Render.DrawCommand>(obj);
			L.Replace(1);
			return 0;
        }
        
        private static int get_Indexs(UniLua.ILuaState L)
        {
			var obj = (SoftwareRenderer.Render.DrawCommand) L.ToUserData(1);
			L.PushAny<MathLib.Vector3[]>(obj.Indexs);
			return 1;
        }
        
        private static int set_Indexs(UniLua.ILuaState L)
        {
			var obj = (SoftwareRenderer.Render.DrawCommand) L.ToUserData(1);
			var value = L.CheckAny<MathLib.Vector3[]>(2);
			obj.Indexs = value;
			// replace old struct
			L.PushAny<SoftwareRenderer.Render.DrawCommand>(obj);
			L.Replace(1);
			return 0;
        }
        
        private static int get_Mat(UniLua.ILuaState L)
        {
			var obj = (SoftwareRenderer.Render.DrawCommand) L.ToUserData(1);
			L.PushAny<SoftwareRenderer.Render.Material>(obj.Mat);
			return 1;
        }
        
        private static int set_Mat(UniLua.ILuaState L)
        {
			var obj = (SoftwareRenderer.Render.DrawCommand) L.ToUserData(1);
			var value = L.CheckAny<SoftwareRenderer.Render.Material>(2);
			obj.Mat = value;
			// replace old struct
			L.PushAny<SoftwareRenderer.Render.DrawCommand>(obj);
			L.Replace(1);
			return 0;
        }
        
        private static int Equals(UniLua.ILuaState L)
        {
			if(L.CheckNum(2) && L.CheckType<SoftwareRenderer.Render.DrawCommand, object>(1))
			{
				bool result;
				var obj = (SoftwareRenderer.Render.DrawCommand) L.ToUserData(1);
				var arg1 = L.CheckAny<object>(2);
				result = obj.Equals(arg1);
				L.PushAny<bool>(result);
				return 1;
			}
			L.L_Error("call function Equals args is error");
			return 1;
        }
        
        private static int GetHashCode(UniLua.ILuaState L)
        {
			if(L.CheckNum(1))
			{
				int result;
				var obj = (SoftwareRenderer.Render.DrawCommand) L.ToUserData(1);
				result = obj.GetHashCode();
				L.PushAny<int>(result);
				return 1;
			}
			L.L_Error("call function GetHashCode args is error");
			return 1;
        }
        
        private static int ToString(UniLua.ILuaState L)
        {
			if(L.CheckNum(1))
			{
				string result;
				var obj = (SoftwareRenderer.Render.DrawCommand) L.ToUserData(1);
				result = obj.ToString();
				L.PushAny<string>(result);
				return 1;
			}
			L.L_Error("call function ToString args is error");
			return 1;
        }
        
        private static int GetType(UniLua.ILuaState L)
        {
			if(L.CheckNum(1))
			{
				System.Type result;
				var obj = (SoftwareRenderer.Render.DrawCommand) L.ToUserData(1);
				result = obj.GetType();
				L.PushAny<System.Type>(result);
				return 1;
			}
			L.L_Error("call function GetType args is error");
			return 1;
        }
    }
}
