//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniToLua
{
    using SoftwareRenderer.Render;
    using System;
    using System.Collections.Generic;
    using MathLib;
    
    
    public class SoftwareRenderer1Render1LuaShaderWrap
    {
        
        public static void Register(UniLua.ILuaState L)
        {
			L.BeginClass(typeof(SoftwareRenderer.Render.LuaShader), typeof(SoftwareRenderer.Render.Shader));
			L.RegFunction("New", _CreateSoftwareRenderer1Render1LuaShader);
			L.RegVar("args", get_args, set_args);
			L.RegFunction("Vertex", Vertex);
			L.RegFunction("Fragment", Fragment);
			L.RegFunction("GetType", GetType);
			L.RegFunction("ToString", ToString);
			L.RegFunction("Equals", Equals);
			L.RegFunction("GetHashCode", GetHashCode);
			L.EndClass();
        }
        
        private static int _CreateSoftwareRenderer1Render1LuaShader(UniLua.ILuaState L)
        {
			if(L.CheckNum(1)&& L.CheckType<string>(1))
			{
				var arg1 = L.CheckAny<string>(1);
				L.PushAny<SoftwareRenderer.Render.LuaShader>(new SoftwareRenderer.Render.LuaShader(arg1));
				return 1;
			}
			L.L_Error("call LuaShader constructor args is error");
			return 1;
        }
        
        private static int get_args(UniLua.ILuaState L)
        {
			var obj = (SoftwareRenderer.Render.LuaShader) L.ToUserData(1);
			L.PushAny<System.Collections.Generic.Dictionary<string, object>>(obj.args);
			return 1;
        }
        
        private static int set_args(UniLua.ILuaState L)
        {
			var obj = (SoftwareRenderer.Render.LuaShader) L.ToUserData(1);
			var value = L.CheckAny<System.Collections.Generic.Dictionary<string, object>>(2);
			obj.args = value;
			return 0;
        }
        
        private static int Vertex(UniLua.ILuaState L)
        {
			if(L.CheckNum(2) && L.CheckType<SoftwareRenderer.Render.LuaShader, SoftwareRenderer.Render.BaseVertexIn>(1))
			{
				SoftwareRenderer.Render.BaseFragmentIn result;
				var obj = (SoftwareRenderer.Render.LuaShader) L.ToUserData(1);
				var arg1 = L.CheckAny<SoftwareRenderer.Render.BaseVertexIn>(2);
				result = obj.Vertex(arg1);
				L.PushAny<SoftwareRenderer.Render.BaseFragmentIn>(result);
				return 1;
			}
			L.L_Error("call function Vertex args is error");
			return 1;
        }
        
        private static int Fragment(UniLua.ILuaState L)
        {
			if(L.CheckNum(2) && L.CheckType<SoftwareRenderer.Render.LuaShader, SoftwareRenderer.Render.BaseFragmentIn>(1))
			{
				MathLib.Color result;
				var obj = (SoftwareRenderer.Render.LuaShader) L.ToUserData(1);
				var arg1 = L.CheckAny<SoftwareRenderer.Render.BaseFragmentIn>(2);
				result = obj.Fragment(arg1);
				L.PushAny<MathLib.Color>(result);
				return 1;
			}
			L.L_Error("call function Fragment args is error");
			return 1;
        }
        
        private static int GetType(UniLua.ILuaState L)
        {
			if(L.CheckNum(1))
			{
				System.Type result;
				var obj = (SoftwareRenderer.Render.LuaShader) L.ToUserData(1);
				result = obj.GetType();
				L.PushAny<System.Type>(result);
				return 1;
			}
			L.L_Error("call function GetType args is error");
			return 1;
        }
        
        private static int ToString(UniLua.ILuaState L)
        {
			if(L.CheckNum(1))
			{
				string result;
				var obj = (SoftwareRenderer.Render.LuaShader) L.ToUserData(1);
				result = obj.ToString();
				L.PushAny<string>(result);
				return 1;
			}
			L.L_Error("call function ToString args is error");
			return 1;
        }
        
        private static int Equals(UniLua.ILuaState L)
        {
			if(L.CheckNum(2) && L.CheckType<SoftwareRenderer.Render.LuaShader, object>(1))
			{
				bool result;
				var obj = (SoftwareRenderer.Render.LuaShader) L.ToUserData(1);
				var arg1 = L.CheckAny<object>(2);
				result = obj.Equals(arg1);
				L.PushAny<bool>(result);
				return 1;
			}
			L.L_Error("call function Equals args is error");
			return 1;
        }
        
        private static int GetHashCode(UniLua.ILuaState L)
        {
			if(L.CheckNum(1))
			{
				int result;
				var obj = (SoftwareRenderer.Render.LuaShader) L.ToUserData(1);
				result = obj.GetHashCode();
				L.PushAny<int>(result);
				return 1;
			}
			L.L_Error("call function GetHashCode args is error");
			return 1;
        }
    }
}
