//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniToLua
{
    using SDL2;
    
    
    public class SDL21SDL_mixer1MIX_InitFlagsWrap
    {
        
        public static void Register(UniLua.ILuaState L)
        {
			L.BeginEnum(typeof(SDL2.SDL_mixer.MIX_InitFlags));
			L.RegVar("MIX_INIT_FLAC", get_MIX_INIT_FLAC, null);
			L.RegVar("MIX_INIT_MOD", get_MIX_INIT_MOD, null);
			L.RegVar("MIX_INIT_MP3", get_MIX_INIT_MP3, null);
			L.RegVar("MIX_INIT_OGG", get_MIX_INIT_OGG, null);
			L.RegVar("MIX_INIT_MID", get_MIX_INIT_MID, null);
			L.RegVar("MIX_INIT_OPUS", get_MIX_INIT_OPUS, null);
			L.EndEnum();
        }
        
        private static int get_MIX_INIT_FLAC(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL_mixer.MIX_InitFlags.MIX_INIT_FLAC);
			return 1;
        }
        
        private static int get_MIX_INIT_MOD(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL_mixer.MIX_InitFlags.MIX_INIT_MOD);
			return 1;
        }
        
        private static int get_MIX_INIT_MP3(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL_mixer.MIX_InitFlags.MIX_INIT_MP3);
			return 1;
        }
        
        private static int get_MIX_INIT_OGG(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL_mixer.MIX_InitFlags.MIX_INIT_OGG);
			return 1;
        }
        
        private static int get_MIX_INIT_MID(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL_mixer.MIX_InitFlags.MIX_INIT_MID);
			return 1;
        }
        
        private static int get_MIX_INIT_OPUS(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL_mixer.MIX_InitFlags.MIX_INIT_OPUS);
			return 1;
        }
    }
}
