//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniToLua
{
    using SDL2;
    
    
    public class SDL21SDL1SDL_KeycodeWrap
    {
        
        public static void Register(UniLua.ILuaState L)
        {
			L.BeginEnum(typeof(SDL2.SDL.SDL_Keycode));
			L.RegVar("SDLK_UNKNOWN", get_SDLK_UNKNOWN, null);
			L.RegVar("SDLK_BACKSPACE", get_SDLK_BACKSPACE, null);
			L.RegVar("SDLK_TAB", get_SDLK_TAB, null);
			L.RegVar("SDLK_RETURN", get_SDLK_RETURN, null);
			L.RegVar("SDLK_ESCAPE", get_SDLK_ESCAPE, null);
			L.RegVar("SDLK_SPACE", get_SDLK_SPACE, null);
			L.RegVar("SDLK_EXCLAIM", get_SDLK_EXCLAIM, null);
			L.RegVar("SDLK_QUOTEDBL", get_SDLK_QUOTEDBL, null);
			L.RegVar("SDLK_HASH", get_SDLK_HASH, null);
			L.RegVar("SDLK_DOLLAR", get_SDLK_DOLLAR, null);
			L.RegVar("SDLK_PERCENT", get_SDLK_PERCENT, null);
			L.RegVar("SDLK_AMPERSAND", get_SDLK_AMPERSAND, null);
			L.RegVar("SDLK_QUOTE", get_SDLK_QUOTE, null);
			L.RegVar("SDLK_LEFTPAREN", get_SDLK_LEFTPAREN, null);
			L.RegVar("SDLK_RIGHTPAREN", get_SDLK_RIGHTPAREN, null);
			L.RegVar("SDLK_ASTERISK", get_SDLK_ASTERISK, null);
			L.RegVar("SDLK_PLUS", get_SDLK_PLUS, null);
			L.RegVar("SDLK_COMMA", get_SDLK_COMMA, null);
			L.RegVar("SDLK_MINUS", get_SDLK_MINUS, null);
			L.RegVar("SDLK_PERIOD", get_SDLK_PERIOD, null);
			L.RegVar("SDLK_SLASH", get_SDLK_SLASH, null);
			L.RegVar("SDLK_0", get_SDLK_0, null);
			L.RegVar("SDLK_1", get_SDLK_1, null);
			L.RegVar("SDLK_2", get_SDLK_2, null);
			L.RegVar("SDLK_3", get_SDLK_3, null);
			L.RegVar("SDLK_4", get_SDLK_4, null);
			L.RegVar("SDLK_5", get_SDLK_5, null);
			L.RegVar("SDLK_6", get_SDLK_6, null);
			L.RegVar("SDLK_7", get_SDLK_7, null);
			L.RegVar("SDLK_8", get_SDLK_8, null);
			L.RegVar("SDLK_9", get_SDLK_9, null);
			L.RegVar("SDLK_COLON", get_SDLK_COLON, null);
			L.RegVar("SDLK_SEMICOLON", get_SDLK_SEMICOLON, null);
			L.RegVar("SDLK_LESS", get_SDLK_LESS, null);
			L.RegVar("SDLK_EQUALS", get_SDLK_EQUALS, null);
			L.RegVar("SDLK_GREATER", get_SDLK_GREATER, null);
			L.RegVar("SDLK_QUESTION", get_SDLK_QUESTION, null);
			L.RegVar("SDLK_AT", get_SDLK_AT, null);
			L.RegVar("SDLK_LEFTBRACKET", get_SDLK_LEFTBRACKET, null);
			L.RegVar("SDLK_BACKSLASH", get_SDLK_BACKSLASH, null);
			L.RegVar("SDLK_RIGHTBRACKET", get_SDLK_RIGHTBRACKET, null);
			L.RegVar("SDLK_CARET", get_SDLK_CARET, null);
			L.RegVar("SDLK_UNDERSCORE", get_SDLK_UNDERSCORE, null);
			L.RegVar("SDLK_BACKQUOTE", get_SDLK_BACKQUOTE, null);
			L.RegVar("SDLK_a", get_SDLK_a, null);
			L.RegVar("SDLK_b", get_SDLK_b, null);
			L.RegVar("SDLK_c", get_SDLK_c, null);
			L.RegVar("SDLK_d", get_SDLK_d, null);
			L.RegVar("SDLK_e", get_SDLK_e, null);
			L.RegVar("SDLK_f", get_SDLK_f, null);
			L.RegVar("SDLK_g", get_SDLK_g, null);
			L.RegVar("SDLK_h", get_SDLK_h, null);
			L.RegVar("SDLK_i", get_SDLK_i, null);
			L.RegVar("SDLK_j", get_SDLK_j, null);
			L.RegVar("SDLK_k", get_SDLK_k, null);
			L.RegVar("SDLK_l", get_SDLK_l, null);
			L.RegVar("SDLK_m", get_SDLK_m, null);
			L.RegVar("SDLK_n", get_SDLK_n, null);
			L.RegVar("SDLK_o", get_SDLK_o, null);
			L.RegVar("SDLK_p", get_SDLK_p, null);
			L.RegVar("SDLK_q", get_SDLK_q, null);
			L.RegVar("SDLK_r", get_SDLK_r, null);
			L.RegVar("SDLK_s", get_SDLK_s, null);
			L.RegVar("SDLK_t", get_SDLK_t, null);
			L.RegVar("SDLK_u", get_SDLK_u, null);
			L.RegVar("SDLK_v", get_SDLK_v, null);
			L.RegVar("SDLK_w", get_SDLK_w, null);
			L.RegVar("SDLK_x", get_SDLK_x, null);
			L.RegVar("SDLK_y", get_SDLK_y, null);
			L.RegVar("SDLK_z", get_SDLK_z, null);
			L.RegVar("SDLK_DELETE", get_SDLK_DELETE, null);
			L.RegVar("SDLK_CAPSLOCK", get_SDLK_CAPSLOCK, null);
			L.RegVar("SDLK_F1", get_SDLK_F1, null);
			L.RegVar("SDLK_F2", get_SDLK_F2, null);
			L.RegVar("SDLK_F3", get_SDLK_F3, null);
			L.RegVar("SDLK_F4", get_SDLK_F4, null);
			L.RegVar("SDLK_F5", get_SDLK_F5, null);
			L.RegVar("SDLK_F6", get_SDLK_F6, null);
			L.RegVar("SDLK_F7", get_SDLK_F7, null);
			L.RegVar("SDLK_F8", get_SDLK_F8, null);
			L.RegVar("SDLK_F9", get_SDLK_F9, null);
			L.RegVar("SDLK_F10", get_SDLK_F10, null);
			L.RegVar("SDLK_F11", get_SDLK_F11, null);
			L.RegVar("SDLK_F12", get_SDLK_F12, null);
			L.RegVar("SDLK_PRINTSCREEN", get_SDLK_PRINTSCREEN, null);
			L.RegVar("SDLK_SCROLLLOCK", get_SDLK_SCROLLLOCK, null);
			L.RegVar("SDLK_PAUSE", get_SDLK_PAUSE, null);
			L.RegVar("SDLK_INSERT", get_SDLK_INSERT, null);
			L.RegVar("SDLK_HOME", get_SDLK_HOME, null);
			L.RegVar("SDLK_PAGEUP", get_SDLK_PAGEUP, null);
			L.RegVar("SDLK_END", get_SDLK_END, null);
			L.RegVar("SDLK_PAGEDOWN", get_SDLK_PAGEDOWN, null);
			L.RegVar("SDLK_RIGHT", get_SDLK_RIGHT, null);
			L.RegVar("SDLK_LEFT", get_SDLK_LEFT, null);
			L.RegVar("SDLK_DOWN", get_SDLK_DOWN, null);
			L.RegVar("SDLK_UP", get_SDLK_UP, null);
			L.RegVar("SDLK_NUMLOCKCLEAR", get_SDLK_NUMLOCKCLEAR, null);
			L.RegVar("SDLK_KP_DIVIDE", get_SDLK_KP_DIVIDE, null);
			L.RegVar("SDLK_KP_MULTIPLY", get_SDLK_KP_MULTIPLY, null);
			L.RegVar("SDLK_KP_MINUS", get_SDLK_KP_MINUS, null);
			L.RegVar("SDLK_KP_PLUS", get_SDLK_KP_PLUS, null);
			L.RegVar("SDLK_KP_ENTER", get_SDLK_KP_ENTER, null);
			L.RegVar("SDLK_KP_1", get_SDLK_KP_1, null);
			L.RegVar("SDLK_KP_2", get_SDLK_KP_2, null);
			L.RegVar("SDLK_KP_3", get_SDLK_KP_3, null);
			L.RegVar("SDLK_KP_4", get_SDLK_KP_4, null);
			L.RegVar("SDLK_KP_5", get_SDLK_KP_5, null);
			L.RegVar("SDLK_KP_6", get_SDLK_KP_6, null);
			L.RegVar("SDLK_KP_7", get_SDLK_KP_7, null);
			L.RegVar("SDLK_KP_8", get_SDLK_KP_8, null);
			L.RegVar("SDLK_KP_9", get_SDLK_KP_9, null);
			L.RegVar("SDLK_KP_0", get_SDLK_KP_0, null);
			L.RegVar("SDLK_KP_PERIOD", get_SDLK_KP_PERIOD, null);
			L.RegVar("SDLK_APPLICATION", get_SDLK_APPLICATION, null);
			L.RegVar("SDLK_POWER", get_SDLK_POWER, null);
			L.RegVar("SDLK_KP_EQUALS", get_SDLK_KP_EQUALS, null);
			L.RegVar("SDLK_F13", get_SDLK_F13, null);
			L.RegVar("SDLK_F14", get_SDLK_F14, null);
			L.RegVar("SDLK_F15", get_SDLK_F15, null);
			L.RegVar("SDLK_F16", get_SDLK_F16, null);
			L.RegVar("SDLK_F17", get_SDLK_F17, null);
			L.RegVar("SDLK_F18", get_SDLK_F18, null);
			L.RegVar("SDLK_F19", get_SDLK_F19, null);
			L.RegVar("SDLK_F20", get_SDLK_F20, null);
			L.RegVar("SDLK_F21", get_SDLK_F21, null);
			L.RegVar("SDLK_F22", get_SDLK_F22, null);
			L.RegVar("SDLK_F23", get_SDLK_F23, null);
			L.RegVar("SDLK_F24", get_SDLK_F24, null);
			L.RegVar("SDLK_EXECUTE", get_SDLK_EXECUTE, null);
			L.RegVar("SDLK_HELP", get_SDLK_HELP, null);
			L.RegVar("SDLK_MENU", get_SDLK_MENU, null);
			L.RegVar("SDLK_SELECT", get_SDLK_SELECT, null);
			L.RegVar("SDLK_STOP", get_SDLK_STOP, null);
			L.RegVar("SDLK_AGAIN", get_SDLK_AGAIN, null);
			L.RegVar("SDLK_UNDO", get_SDLK_UNDO, null);
			L.RegVar("SDLK_CUT", get_SDLK_CUT, null);
			L.RegVar("SDLK_COPY", get_SDLK_COPY, null);
			L.RegVar("SDLK_PASTE", get_SDLK_PASTE, null);
			L.RegVar("SDLK_FIND", get_SDLK_FIND, null);
			L.RegVar("SDLK_MUTE", get_SDLK_MUTE, null);
			L.RegVar("SDLK_VOLUMEUP", get_SDLK_VOLUMEUP, null);
			L.RegVar("SDLK_VOLUMEDOWN", get_SDLK_VOLUMEDOWN, null);
			L.RegVar("SDLK_KP_COMMA", get_SDLK_KP_COMMA, null);
			L.RegVar("SDLK_KP_EQUALSAS400", get_SDLK_KP_EQUALSAS400, null);
			L.RegVar("SDLK_ALTERASE", get_SDLK_ALTERASE, null);
			L.RegVar("SDLK_SYSREQ", get_SDLK_SYSREQ, null);
			L.RegVar("SDLK_CANCEL", get_SDLK_CANCEL, null);
			L.RegVar("SDLK_CLEAR", get_SDLK_CLEAR, null);
			L.RegVar("SDLK_PRIOR", get_SDLK_PRIOR, null);
			L.RegVar("SDLK_RETURN2", get_SDLK_RETURN2, null);
			L.RegVar("SDLK_SEPARATOR", get_SDLK_SEPARATOR, null);
			L.RegVar("SDLK_OUT", get_SDLK_OUT, null);
			L.RegVar("SDLK_OPER", get_SDLK_OPER, null);
			L.RegVar("SDLK_CLEARAGAIN", get_SDLK_CLEARAGAIN, null);
			L.RegVar("SDLK_CRSEL", get_SDLK_CRSEL, null);
			L.RegVar("SDLK_EXSEL", get_SDLK_EXSEL, null);
			L.RegVar("SDLK_KP_00", get_SDLK_KP_00, null);
			L.RegVar("SDLK_KP_000", get_SDLK_KP_000, null);
			L.RegVar("SDLK_THOUSANDSSEPARATOR", get_SDLK_THOUSANDSSEPARATOR, null);
			L.RegVar("SDLK_DECIMALSEPARATOR", get_SDLK_DECIMALSEPARATOR, null);
			L.RegVar("SDLK_CURRENCYUNIT", get_SDLK_CURRENCYUNIT, null);
			L.RegVar("SDLK_CURRENCYSUBUNIT", get_SDLK_CURRENCYSUBUNIT, null);
			L.RegVar("SDLK_KP_LEFTPAREN", get_SDLK_KP_LEFTPAREN, null);
			L.RegVar("SDLK_KP_RIGHTPAREN", get_SDLK_KP_RIGHTPAREN, null);
			L.RegVar("SDLK_KP_LEFTBRACE", get_SDLK_KP_LEFTBRACE, null);
			L.RegVar("SDLK_KP_RIGHTBRACE", get_SDLK_KP_RIGHTBRACE, null);
			L.RegVar("SDLK_KP_TAB", get_SDLK_KP_TAB, null);
			L.RegVar("SDLK_KP_BACKSPACE", get_SDLK_KP_BACKSPACE, null);
			L.RegVar("SDLK_KP_A", get_SDLK_KP_A, null);
			L.RegVar("SDLK_KP_B", get_SDLK_KP_B, null);
			L.RegVar("SDLK_KP_C", get_SDLK_KP_C, null);
			L.RegVar("SDLK_KP_D", get_SDLK_KP_D, null);
			L.RegVar("SDLK_KP_E", get_SDLK_KP_E, null);
			L.RegVar("SDLK_KP_F", get_SDLK_KP_F, null);
			L.RegVar("SDLK_KP_XOR", get_SDLK_KP_XOR, null);
			L.RegVar("SDLK_KP_POWER", get_SDLK_KP_POWER, null);
			L.RegVar("SDLK_KP_PERCENT", get_SDLK_KP_PERCENT, null);
			L.RegVar("SDLK_KP_LESS", get_SDLK_KP_LESS, null);
			L.RegVar("SDLK_KP_GREATER", get_SDLK_KP_GREATER, null);
			L.RegVar("SDLK_KP_AMPERSAND", get_SDLK_KP_AMPERSAND, null);
			L.RegVar("SDLK_KP_DBLAMPERSAND", get_SDLK_KP_DBLAMPERSAND, null);
			L.RegVar("SDLK_KP_VERTICALBAR", get_SDLK_KP_VERTICALBAR, null);
			L.RegVar("SDLK_KP_DBLVERTICALBAR", get_SDLK_KP_DBLVERTICALBAR, null);
			L.RegVar("SDLK_KP_COLON", get_SDLK_KP_COLON, null);
			L.RegVar("SDLK_KP_HASH", get_SDLK_KP_HASH, null);
			L.RegVar("SDLK_KP_SPACE", get_SDLK_KP_SPACE, null);
			L.RegVar("SDLK_KP_AT", get_SDLK_KP_AT, null);
			L.RegVar("SDLK_KP_EXCLAM", get_SDLK_KP_EXCLAM, null);
			L.RegVar("SDLK_KP_MEMSTORE", get_SDLK_KP_MEMSTORE, null);
			L.RegVar("SDLK_KP_MEMRECALL", get_SDLK_KP_MEMRECALL, null);
			L.RegVar("SDLK_KP_MEMCLEAR", get_SDLK_KP_MEMCLEAR, null);
			L.RegVar("SDLK_KP_MEMADD", get_SDLK_KP_MEMADD, null);
			L.RegVar("SDLK_KP_MEMSUBTRACT", get_SDLK_KP_MEMSUBTRACT, null);
			L.RegVar("SDLK_KP_MEMMULTIPLY", get_SDLK_KP_MEMMULTIPLY, null);
			L.RegVar("SDLK_KP_MEMDIVIDE", get_SDLK_KP_MEMDIVIDE, null);
			L.RegVar("SDLK_KP_PLUSMINUS", get_SDLK_KP_PLUSMINUS, null);
			L.RegVar("SDLK_KP_CLEAR", get_SDLK_KP_CLEAR, null);
			L.RegVar("SDLK_KP_CLEARENTRY", get_SDLK_KP_CLEARENTRY, null);
			L.RegVar("SDLK_KP_BINARY", get_SDLK_KP_BINARY, null);
			L.RegVar("SDLK_KP_OCTAL", get_SDLK_KP_OCTAL, null);
			L.RegVar("SDLK_KP_DECIMAL", get_SDLK_KP_DECIMAL, null);
			L.RegVar("SDLK_KP_HEXADECIMAL", get_SDLK_KP_HEXADECIMAL, null);
			L.RegVar("SDLK_LCTRL", get_SDLK_LCTRL, null);
			L.RegVar("SDLK_LSHIFT", get_SDLK_LSHIFT, null);
			L.RegVar("SDLK_LALT", get_SDLK_LALT, null);
			L.RegVar("SDLK_LGUI", get_SDLK_LGUI, null);
			L.RegVar("SDLK_RCTRL", get_SDLK_RCTRL, null);
			L.RegVar("SDLK_RSHIFT", get_SDLK_RSHIFT, null);
			L.RegVar("SDLK_RALT", get_SDLK_RALT, null);
			L.RegVar("SDLK_RGUI", get_SDLK_RGUI, null);
			L.RegVar("SDLK_MODE", get_SDLK_MODE, null);
			L.RegVar("SDLK_AUDIONEXT", get_SDLK_AUDIONEXT, null);
			L.RegVar("SDLK_AUDIOPREV", get_SDLK_AUDIOPREV, null);
			L.RegVar("SDLK_AUDIOSTOP", get_SDLK_AUDIOSTOP, null);
			L.RegVar("SDLK_AUDIOPLAY", get_SDLK_AUDIOPLAY, null);
			L.RegVar("SDLK_AUDIOMUTE", get_SDLK_AUDIOMUTE, null);
			L.RegVar("SDLK_MEDIASELECT", get_SDLK_MEDIASELECT, null);
			L.RegVar("SDLK_WWW", get_SDLK_WWW, null);
			L.RegVar("SDLK_MAIL", get_SDLK_MAIL, null);
			L.RegVar("SDLK_CALCULATOR", get_SDLK_CALCULATOR, null);
			L.RegVar("SDLK_COMPUTER", get_SDLK_COMPUTER, null);
			L.RegVar("SDLK_AC_SEARCH", get_SDLK_AC_SEARCH, null);
			L.RegVar("SDLK_AC_HOME", get_SDLK_AC_HOME, null);
			L.RegVar("SDLK_AC_BACK", get_SDLK_AC_BACK, null);
			L.RegVar("SDLK_AC_FORWARD", get_SDLK_AC_FORWARD, null);
			L.RegVar("SDLK_AC_STOP", get_SDLK_AC_STOP, null);
			L.RegVar("SDLK_AC_REFRESH", get_SDLK_AC_REFRESH, null);
			L.RegVar("SDLK_AC_BOOKMARKS", get_SDLK_AC_BOOKMARKS, null);
			L.RegVar("SDLK_BRIGHTNESSDOWN", get_SDLK_BRIGHTNESSDOWN, null);
			L.RegVar("SDLK_BRIGHTNESSUP", get_SDLK_BRIGHTNESSUP, null);
			L.RegVar("SDLK_DISPLAYSWITCH", get_SDLK_DISPLAYSWITCH, null);
			L.RegVar("SDLK_KBDILLUMTOGGLE", get_SDLK_KBDILLUMTOGGLE, null);
			L.RegVar("SDLK_KBDILLUMDOWN", get_SDLK_KBDILLUMDOWN, null);
			L.RegVar("SDLK_KBDILLUMUP", get_SDLK_KBDILLUMUP, null);
			L.RegVar("SDLK_EJECT", get_SDLK_EJECT, null);
			L.RegVar("SDLK_SLEEP", get_SDLK_SLEEP, null);
			L.RegVar("SDLK_APP1", get_SDLK_APP1, null);
			L.RegVar("SDLK_APP2", get_SDLK_APP2, null);
			L.RegVar("SDLK_AUDIOREWIND", get_SDLK_AUDIOREWIND, null);
			L.RegVar("SDLK_AUDIOFASTFORWARD", get_SDLK_AUDIOFASTFORWARD, null);
			L.EndEnum();
        }
        
        private static int get_SDLK_UNKNOWN(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_UNKNOWN);
			return 1;
        }
        
        private static int get_SDLK_BACKSPACE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_BACKSPACE);
			return 1;
        }
        
        private static int get_SDLK_TAB(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_TAB);
			return 1;
        }
        
        private static int get_SDLK_RETURN(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_RETURN);
			return 1;
        }
        
        private static int get_SDLK_ESCAPE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_ESCAPE);
			return 1;
        }
        
        private static int get_SDLK_SPACE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_SPACE);
			return 1;
        }
        
        private static int get_SDLK_EXCLAIM(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_EXCLAIM);
			return 1;
        }
        
        private static int get_SDLK_QUOTEDBL(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_QUOTEDBL);
			return 1;
        }
        
        private static int get_SDLK_HASH(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_HASH);
			return 1;
        }
        
        private static int get_SDLK_DOLLAR(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_DOLLAR);
			return 1;
        }
        
        private static int get_SDLK_PERCENT(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_PERCENT);
			return 1;
        }
        
        private static int get_SDLK_AMPERSAND(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_AMPERSAND);
			return 1;
        }
        
        private static int get_SDLK_QUOTE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_QUOTE);
			return 1;
        }
        
        private static int get_SDLK_LEFTPAREN(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_LEFTPAREN);
			return 1;
        }
        
        private static int get_SDLK_RIGHTPAREN(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_RIGHTPAREN);
			return 1;
        }
        
        private static int get_SDLK_ASTERISK(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_ASTERISK);
			return 1;
        }
        
        private static int get_SDLK_PLUS(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_PLUS);
			return 1;
        }
        
        private static int get_SDLK_COMMA(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_COMMA);
			return 1;
        }
        
        private static int get_SDLK_MINUS(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_MINUS);
			return 1;
        }
        
        private static int get_SDLK_PERIOD(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_PERIOD);
			return 1;
        }
        
        private static int get_SDLK_SLASH(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_SLASH);
			return 1;
        }
        
        private static int get_SDLK_0(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_0);
			return 1;
        }
        
        private static int get_SDLK_1(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_1);
			return 1;
        }
        
        private static int get_SDLK_2(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_2);
			return 1;
        }
        
        private static int get_SDLK_3(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_3);
			return 1;
        }
        
        private static int get_SDLK_4(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_4);
			return 1;
        }
        
        private static int get_SDLK_5(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_5);
			return 1;
        }
        
        private static int get_SDLK_6(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_6);
			return 1;
        }
        
        private static int get_SDLK_7(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_7);
			return 1;
        }
        
        private static int get_SDLK_8(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_8);
			return 1;
        }
        
        private static int get_SDLK_9(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_9);
			return 1;
        }
        
        private static int get_SDLK_COLON(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_COLON);
			return 1;
        }
        
        private static int get_SDLK_SEMICOLON(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_SEMICOLON);
			return 1;
        }
        
        private static int get_SDLK_LESS(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_LESS);
			return 1;
        }
        
        private static int get_SDLK_EQUALS(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_EQUALS);
			return 1;
        }
        
        private static int get_SDLK_GREATER(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_GREATER);
			return 1;
        }
        
        private static int get_SDLK_QUESTION(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_QUESTION);
			return 1;
        }
        
        private static int get_SDLK_AT(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_AT);
			return 1;
        }
        
        private static int get_SDLK_LEFTBRACKET(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_LEFTBRACKET);
			return 1;
        }
        
        private static int get_SDLK_BACKSLASH(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_BACKSLASH);
			return 1;
        }
        
        private static int get_SDLK_RIGHTBRACKET(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_RIGHTBRACKET);
			return 1;
        }
        
        private static int get_SDLK_CARET(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_CARET);
			return 1;
        }
        
        private static int get_SDLK_UNDERSCORE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_UNDERSCORE);
			return 1;
        }
        
        private static int get_SDLK_BACKQUOTE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_BACKQUOTE);
			return 1;
        }
        
        private static int get_SDLK_a(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_a);
			return 1;
        }
        
        private static int get_SDLK_b(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_b);
			return 1;
        }
        
        private static int get_SDLK_c(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_c);
			return 1;
        }
        
        private static int get_SDLK_d(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_d);
			return 1;
        }
        
        private static int get_SDLK_e(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_e);
			return 1;
        }
        
        private static int get_SDLK_f(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_f);
			return 1;
        }
        
        private static int get_SDLK_g(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_g);
			return 1;
        }
        
        private static int get_SDLK_h(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_h);
			return 1;
        }
        
        private static int get_SDLK_i(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_i);
			return 1;
        }
        
        private static int get_SDLK_j(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_j);
			return 1;
        }
        
        private static int get_SDLK_k(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_k);
			return 1;
        }
        
        private static int get_SDLK_l(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_l);
			return 1;
        }
        
        private static int get_SDLK_m(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_m);
			return 1;
        }
        
        private static int get_SDLK_n(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_n);
			return 1;
        }
        
        private static int get_SDLK_o(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_o);
			return 1;
        }
        
        private static int get_SDLK_p(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_p);
			return 1;
        }
        
        private static int get_SDLK_q(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_q);
			return 1;
        }
        
        private static int get_SDLK_r(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_r);
			return 1;
        }
        
        private static int get_SDLK_s(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_s);
			return 1;
        }
        
        private static int get_SDLK_t(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_t);
			return 1;
        }
        
        private static int get_SDLK_u(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_u);
			return 1;
        }
        
        private static int get_SDLK_v(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_v);
			return 1;
        }
        
        private static int get_SDLK_w(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_w);
			return 1;
        }
        
        private static int get_SDLK_x(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_x);
			return 1;
        }
        
        private static int get_SDLK_y(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_y);
			return 1;
        }
        
        private static int get_SDLK_z(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_z);
			return 1;
        }
        
        private static int get_SDLK_DELETE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_DELETE);
			return 1;
        }
        
        private static int get_SDLK_CAPSLOCK(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_CAPSLOCK);
			return 1;
        }
        
        private static int get_SDLK_F1(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_F1);
			return 1;
        }
        
        private static int get_SDLK_F2(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_F2);
			return 1;
        }
        
        private static int get_SDLK_F3(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_F3);
			return 1;
        }
        
        private static int get_SDLK_F4(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_F4);
			return 1;
        }
        
        private static int get_SDLK_F5(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_F5);
			return 1;
        }
        
        private static int get_SDLK_F6(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_F6);
			return 1;
        }
        
        private static int get_SDLK_F7(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_F7);
			return 1;
        }
        
        private static int get_SDLK_F8(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_F8);
			return 1;
        }
        
        private static int get_SDLK_F9(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_F9);
			return 1;
        }
        
        private static int get_SDLK_F10(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_F10);
			return 1;
        }
        
        private static int get_SDLK_F11(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_F11);
			return 1;
        }
        
        private static int get_SDLK_F12(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_F12);
			return 1;
        }
        
        private static int get_SDLK_PRINTSCREEN(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_PRINTSCREEN);
			return 1;
        }
        
        private static int get_SDLK_SCROLLLOCK(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_SCROLLLOCK);
			return 1;
        }
        
        private static int get_SDLK_PAUSE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_PAUSE);
			return 1;
        }
        
        private static int get_SDLK_INSERT(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_INSERT);
			return 1;
        }
        
        private static int get_SDLK_HOME(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_HOME);
			return 1;
        }
        
        private static int get_SDLK_PAGEUP(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_PAGEUP);
			return 1;
        }
        
        private static int get_SDLK_END(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_END);
			return 1;
        }
        
        private static int get_SDLK_PAGEDOWN(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_PAGEDOWN);
			return 1;
        }
        
        private static int get_SDLK_RIGHT(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_RIGHT);
			return 1;
        }
        
        private static int get_SDLK_LEFT(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_LEFT);
			return 1;
        }
        
        private static int get_SDLK_DOWN(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_DOWN);
			return 1;
        }
        
        private static int get_SDLK_UP(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_UP);
			return 1;
        }
        
        private static int get_SDLK_NUMLOCKCLEAR(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_NUMLOCKCLEAR);
			return 1;
        }
        
        private static int get_SDLK_KP_DIVIDE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_DIVIDE);
			return 1;
        }
        
        private static int get_SDLK_KP_MULTIPLY(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_MULTIPLY);
			return 1;
        }
        
        private static int get_SDLK_KP_MINUS(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_MINUS);
			return 1;
        }
        
        private static int get_SDLK_KP_PLUS(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_PLUS);
			return 1;
        }
        
        private static int get_SDLK_KP_ENTER(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_ENTER);
			return 1;
        }
        
        private static int get_SDLK_KP_1(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_1);
			return 1;
        }
        
        private static int get_SDLK_KP_2(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_2);
			return 1;
        }
        
        private static int get_SDLK_KP_3(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_3);
			return 1;
        }
        
        private static int get_SDLK_KP_4(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_4);
			return 1;
        }
        
        private static int get_SDLK_KP_5(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_5);
			return 1;
        }
        
        private static int get_SDLK_KP_6(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_6);
			return 1;
        }
        
        private static int get_SDLK_KP_7(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_7);
			return 1;
        }
        
        private static int get_SDLK_KP_8(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_8);
			return 1;
        }
        
        private static int get_SDLK_KP_9(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_9);
			return 1;
        }
        
        private static int get_SDLK_KP_0(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_0);
			return 1;
        }
        
        private static int get_SDLK_KP_PERIOD(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_PERIOD);
			return 1;
        }
        
        private static int get_SDLK_APPLICATION(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_APPLICATION);
			return 1;
        }
        
        private static int get_SDLK_POWER(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_POWER);
			return 1;
        }
        
        private static int get_SDLK_KP_EQUALS(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_EQUALS);
			return 1;
        }
        
        private static int get_SDLK_F13(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_F13);
			return 1;
        }
        
        private static int get_SDLK_F14(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_F14);
			return 1;
        }
        
        private static int get_SDLK_F15(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_F15);
			return 1;
        }
        
        private static int get_SDLK_F16(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_F16);
			return 1;
        }
        
        private static int get_SDLK_F17(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_F17);
			return 1;
        }
        
        private static int get_SDLK_F18(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_F18);
			return 1;
        }
        
        private static int get_SDLK_F19(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_F19);
			return 1;
        }
        
        private static int get_SDLK_F20(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_F20);
			return 1;
        }
        
        private static int get_SDLK_F21(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_F21);
			return 1;
        }
        
        private static int get_SDLK_F22(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_F22);
			return 1;
        }
        
        private static int get_SDLK_F23(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_F23);
			return 1;
        }
        
        private static int get_SDLK_F24(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_F24);
			return 1;
        }
        
        private static int get_SDLK_EXECUTE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_EXECUTE);
			return 1;
        }
        
        private static int get_SDLK_HELP(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_HELP);
			return 1;
        }
        
        private static int get_SDLK_MENU(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_MENU);
			return 1;
        }
        
        private static int get_SDLK_SELECT(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_SELECT);
			return 1;
        }
        
        private static int get_SDLK_STOP(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_STOP);
			return 1;
        }
        
        private static int get_SDLK_AGAIN(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_AGAIN);
			return 1;
        }
        
        private static int get_SDLK_UNDO(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_UNDO);
			return 1;
        }
        
        private static int get_SDLK_CUT(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_CUT);
			return 1;
        }
        
        private static int get_SDLK_COPY(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_COPY);
			return 1;
        }
        
        private static int get_SDLK_PASTE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_PASTE);
			return 1;
        }
        
        private static int get_SDLK_FIND(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_FIND);
			return 1;
        }
        
        private static int get_SDLK_MUTE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_MUTE);
			return 1;
        }
        
        private static int get_SDLK_VOLUMEUP(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_VOLUMEUP);
			return 1;
        }
        
        private static int get_SDLK_VOLUMEDOWN(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_VOLUMEDOWN);
			return 1;
        }
        
        private static int get_SDLK_KP_COMMA(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_COMMA);
			return 1;
        }
        
        private static int get_SDLK_KP_EQUALSAS400(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_EQUALSAS400);
			return 1;
        }
        
        private static int get_SDLK_ALTERASE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_ALTERASE);
			return 1;
        }
        
        private static int get_SDLK_SYSREQ(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_SYSREQ);
			return 1;
        }
        
        private static int get_SDLK_CANCEL(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_CANCEL);
			return 1;
        }
        
        private static int get_SDLK_CLEAR(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_CLEAR);
			return 1;
        }
        
        private static int get_SDLK_PRIOR(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_PRIOR);
			return 1;
        }
        
        private static int get_SDLK_RETURN2(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_RETURN2);
			return 1;
        }
        
        private static int get_SDLK_SEPARATOR(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_SEPARATOR);
			return 1;
        }
        
        private static int get_SDLK_OUT(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_OUT);
			return 1;
        }
        
        private static int get_SDLK_OPER(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_OPER);
			return 1;
        }
        
        private static int get_SDLK_CLEARAGAIN(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_CLEARAGAIN);
			return 1;
        }
        
        private static int get_SDLK_CRSEL(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_CRSEL);
			return 1;
        }
        
        private static int get_SDLK_EXSEL(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_EXSEL);
			return 1;
        }
        
        private static int get_SDLK_KP_00(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_00);
			return 1;
        }
        
        private static int get_SDLK_KP_000(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_000);
			return 1;
        }
        
        private static int get_SDLK_THOUSANDSSEPARATOR(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_THOUSANDSSEPARATOR);
			return 1;
        }
        
        private static int get_SDLK_DECIMALSEPARATOR(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_DECIMALSEPARATOR);
			return 1;
        }
        
        private static int get_SDLK_CURRENCYUNIT(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_CURRENCYUNIT);
			return 1;
        }
        
        private static int get_SDLK_CURRENCYSUBUNIT(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_CURRENCYSUBUNIT);
			return 1;
        }
        
        private static int get_SDLK_KP_LEFTPAREN(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_LEFTPAREN);
			return 1;
        }
        
        private static int get_SDLK_KP_RIGHTPAREN(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_RIGHTPAREN);
			return 1;
        }
        
        private static int get_SDLK_KP_LEFTBRACE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_LEFTBRACE);
			return 1;
        }
        
        private static int get_SDLK_KP_RIGHTBRACE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_RIGHTBRACE);
			return 1;
        }
        
        private static int get_SDLK_KP_TAB(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_TAB);
			return 1;
        }
        
        private static int get_SDLK_KP_BACKSPACE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_BACKSPACE);
			return 1;
        }
        
        private static int get_SDLK_KP_A(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_A);
			return 1;
        }
        
        private static int get_SDLK_KP_B(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_B);
			return 1;
        }
        
        private static int get_SDLK_KP_C(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_C);
			return 1;
        }
        
        private static int get_SDLK_KP_D(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_D);
			return 1;
        }
        
        private static int get_SDLK_KP_E(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_E);
			return 1;
        }
        
        private static int get_SDLK_KP_F(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_F);
			return 1;
        }
        
        private static int get_SDLK_KP_XOR(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_XOR);
			return 1;
        }
        
        private static int get_SDLK_KP_POWER(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_POWER);
			return 1;
        }
        
        private static int get_SDLK_KP_PERCENT(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_PERCENT);
			return 1;
        }
        
        private static int get_SDLK_KP_LESS(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_LESS);
			return 1;
        }
        
        private static int get_SDLK_KP_GREATER(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_GREATER);
			return 1;
        }
        
        private static int get_SDLK_KP_AMPERSAND(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_AMPERSAND);
			return 1;
        }
        
        private static int get_SDLK_KP_DBLAMPERSAND(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_DBLAMPERSAND);
			return 1;
        }
        
        private static int get_SDLK_KP_VERTICALBAR(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_VERTICALBAR);
			return 1;
        }
        
        private static int get_SDLK_KP_DBLVERTICALBAR(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_DBLVERTICALBAR);
			return 1;
        }
        
        private static int get_SDLK_KP_COLON(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_COLON);
			return 1;
        }
        
        private static int get_SDLK_KP_HASH(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_HASH);
			return 1;
        }
        
        private static int get_SDLK_KP_SPACE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_SPACE);
			return 1;
        }
        
        private static int get_SDLK_KP_AT(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_AT);
			return 1;
        }
        
        private static int get_SDLK_KP_EXCLAM(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_EXCLAM);
			return 1;
        }
        
        private static int get_SDLK_KP_MEMSTORE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_MEMSTORE);
			return 1;
        }
        
        private static int get_SDLK_KP_MEMRECALL(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_MEMRECALL);
			return 1;
        }
        
        private static int get_SDLK_KP_MEMCLEAR(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_MEMCLEAR);
			return 1;
        }
        
        private static int get_SDLK_KP_MEMADD(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_MEMADD);
			return 1;
        }
        
        private static int get_SDLK_KP_MEMSUBTRACT(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_MEMSUBTRACT);
			return 1;
        }
        
        private static int get_SDLK_KP_MEMMULTIPLY(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_MEMMULTIPLY);
			return 1;
        }
        
        private static int get_SDLK_KP_MEMDIVIDE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_MEMDIVIDE);
			return 1;
        }
        
        private static int get_SDLK_KP_PLUSMINUS(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_PLUSMINUS);
			return 1;
        }
        
        private static int get_SDLK_KP_CLEAR(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_CLEAR);
			return 1;
        }
        
        private static int get_SDLK_KP_CLEARENTRY(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_CLEARENTRY);
			return 1;
        }
        
        private static int get_SDLK_KP_BINARY(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_BINARY);
			return 1;
        }
        
        private static int get_SDLK_KP_OCTAL(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_OCTAL);
			return 1;
        }
        
        private static int get_SDLK_KP_DECIMAL(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_DECIMAL);
			return 1;
        }
        
        private static int get_SDLK_KP_HEXADECIMAL(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KP_HEXADECIMAL);
			return 1;
        }
        
        private static int get_SDLK_LCTRL(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_LCTRL);
			return 1;
        }
        
        private static int get_SDLK_LSHIFT(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_LSHIFT);
			return 1;
        }
        
        private static int get_SDLK_LALT(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_LALT);
			return 1;
        }
        
        private static int get_SDLK_LGUI(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_LGUI);
			return 1;
        }
        
        private static int get_SDLK_RCTRL(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_RCTRL);
			return 1;
        }
        
        private static int get_SDLK_RSHIFT(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_RSHIFT);
			return 1;
        }
        
        private static int get_SDLK_RALT(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_RALT);
			return 1;
        }
        
        private static int get_SDLK_RGUI(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_RGUI);
			return 1;
        }
        
        private static int get_SDLK_MODE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_MODE);
			return 1;
        }
        
        private static int get_SDLK_AUDIONEXT(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_AUDIONEXT);
			return 1;
        }
        
        private static int get_SDLK_AUDIOPREV(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_AUDIOPREV);
			return 1;
        }
        
        private static int get_SDLK_AUDIOSTOP(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_AUDIOSTOP);
			return 1;
        }
        
        private static int get_SDLK_AUDIOPLAY(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_AUDIOPLAY);
			return 1;
        }
        
        private static int get_SDLK_AUDIOMUTE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_AUDIOMUTE);
			return 1;
        }
        
        private static int get_SDLK_MEDIASELECT(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_MEDIASELECT);
			return 1;
        }
        
        private static int get_SDLK_WWW(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_WWW);
			return 1;
        }
        
        private static int get_SDLK_MAIL(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_MAIL);
			return 1;
        }
        
        private static int get_SDLK_CALCULATOR(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_CALCULATOR);
			return 1;
        }
        
        private static int get_SDLK_COMPUTER(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_COMPUTER);
			return 1;
        }
        
        private static int get_SDLK_AC_SEARCH(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_AC_SEARCH);
			return 1;
        }
        
        private static int get_SDLK_AC_HOME(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_AC_HOME);
			return 1;
        }
        
        private static int get_SDLK_AC_BACK(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_AC_BACK);
			return 1;
        }
        
        private static int get_SDLK_AC_FORWARD(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_AC_FORWARD);
			return 1;
        }
        
        private static int get_SDLK_AC_STOP(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_AC_STOP);
			return 1;
        }
        
        private static int get_SDLK_AC_REFRESH(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_AC_REFRESH);
			return 1;
        }
        
        private static int get_SDLK_AC_BOOKMARKS(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_AC_BOOKMARKS);
			return 1;
        }
        
        private static int get_SDLK_BRIGHTNESSDOWN(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_BRIGHTNESSDOWN);
			return 1;
        }
        
        private static int get_SDLK_BRIGHTNESSUP(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_BRIGHTNESSUP);
			return 1;
        }
        
        private static int get_SDLK_DISPLAYSWITCH(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_DISPLAYSWITCH);
			return 1;
        }
        
        private static int get_SDLK_KBDILLUMTOGGLE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KBDILLUMTOGGLE);
			return 1;
        }
        
        private static int get_SDLK_KBDILLUMDOWN(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KBDILLUMDOWN);
			return 1;
        }
        
        private static int get_SDLK_KBDILLUMUP(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_KBDILLUMUP);
			return 1;
        }
        
        private static int get_SDLK_EJECT(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_EJECT);
			return 1;
        }
        
        private static int get_SDLK_SLEEP(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_SLEEP);
			return 1;
        }
        
        private static int get_SDLK_APP1(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_APP1);
			return 1;
        }
        
        private static int get_SDLK_APP2(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_APP2);
			return 1;
        }
        
        private static int get_SDLK_AUDIOREWIND(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_AUDIOREWIND);
			return 1;
        }
        
        private static int get_SDLK_AUDIOFASTFORWARD(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_Keycode.SDLK_AUDIOFASTFORWARD);
			return 1;
        }
    }
}
