//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniToLua
{
    using SDL2;
    using System;
    
    
    public class SDL21SDL1INTERNAL_GameControllerButtonBind_unionWrap
    {
        
        public static void Register(UniLua.ILuaState L)
        {
			L.BeginClass(typeof(SDL2.SDL.INTERNAL_GameControllerButtonBind_union), typeof(System.ValueType));
			L.RegFunction("New", _CreateSDL21SDL1INTERNAL_GameControllerButtonBind_union);
			L.RegVar("button", get_button, set_button);
			L.RegVar("axis", get_axis, set_axis);
			L.RegVar("hat", get_hat, set_hat);
			L.RegFunction("Equals", Equals);
			L.RegFunction("GetHashCode", GetHashCode);
			L.RegFunction("ToString", ToString);
			L.RegFunction("GetType", GetType);
			L.EndClass();
        }
        
        private static int _CreateSDL21SDL1INTERNAL_GameControllerButtonBind_union(UniLua.ILuaState L)
        {
			if(L.CheckNum(0)) {
				L.PushAny<SDL2.SDL.INTERNAL_GameControllerButtonBind_union>(default(SDL2.SDL.INTERNAL_GameControllerButtonBind_union));
				return 1;
			}
			L.L_Error("call INTERNAL_GameControllerButtonBind_union constructor args is error");
			return 1;
        }
        
        private static int get_button(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.INTERNAL_GameControllerButtonBind_union) L.ToUserData(1);
			L.PushAny<int>(obj.button);
			return 1;
        }
        
        private static int set_button(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.INTERNAL_GameControllerButtonBind_union) L.ToUserData(1);
			var value = L.CheckAny<int>(2);
			obj.button = value;
			return 0;
        }
        
        private static int get_axis(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.INTERNAL_GameControllerButtonBind_union) L.ToUserData(1);
			L.PushAny<int>(obj.axis);
			return 1;
        }
        
        private static int set_axis(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.INTERNAL_GameControllerButtonBind_union) L.ToUserData(1);
			var value = L.CheckAny<int>(2);
			obj.axis = value;
			return 0;
        }
        
        private static int get_hat(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.INTERNAL_GameControllerButtonBind_union) L.ToUserData(1);
			L.PushAny<SDL2.SDL.INTERNAL_GameControllerButtonBind_hat>(obj.hat);
			return 1;
        }
        
        private static int set_hat(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.INTERNAL_GameControllerButtonBind_union) L.ToUserData(1);
			var value = L.CheckAny<SDL2.SDL.INTERNAL_GameControllerButtonBind_hat>(2);
			obj.hat = value;
			return 0;
        }
        
        private static int Equals(UniLua.ILuaState L)
        {
			if(L.CheckNum(2) && L.CheckType<SDL2.SDL.INTERNAL_GameControllerButtonBind_union, object>(1))
			{
				bool result;
				var obj = (SDL2.SDL.INTERNAL_GameControllerButtonBind_union) L.ToUserData(1);
				var arg1 = L.CheckAny<object>(2);
				result = obj.Equals(arg1);
				L.PushAny<bool>(result);
				return 1;
			}
			L.L_Error("call function Equals args is error");
			return 1;
        }
        
        private static int GetHashCode(UniLua.ILuaState L)
        {
			if(L.CheckNum(1))
			{
				int result;
				var obj = (SDL2.SDL.INTERNAL_GameControllerButtonBind_union) L.ToUserData(1);
				result = obj.GetHashCode();
				L.PushAny<int>(result);
				return 1;
			}
			L.L_Error("call function GetHashCode args is error");
			return 1;
        }
        
        private static int ToString(UniLua.ILuaState L)
        {
			if(L.CheckNum(1))
			{
				string result;
				var obj = (SDL2.SDL.INTERNAL_GameControllerButtonBind_union) L.ToUserData(1);
				result = obj.ToString();
				L.PushAny<string>(result);
				return 1;
			}
			L.L_Error("call function ToString args is error");
			return 1;
        }
        
        private static int GetType(UniLua.ILuaState L)
        {
			if(L.CheckNum(1))
			{
				System.Type result;
				var obj = (SDL2.SDL.INTERNAL_GameControllerButtonBind_union) L.ToUserData(1);
				result = obj.GetType();
				L.PushAny<System.Type>(result);
				return 1;
			}
			L.L_Error("call function GetType args is error");
			return 1;
        }
    }
}
