//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniToLua
{
    using SDL2;
    
    
    public class SDL21SDL1SDL_SensorTypeWrap
    {
        
        public static void Register(UniLua.ILuaState L)
        {
			L.BeginEnum(typeof(SDL2.SDL.SDL_SensorType));
			L.RegVar("SDL_SENSOR_UNKNOWN", get_SDL_SENSOR_UNKNOWN, null);
			L.RegVar("SDL_SENSOR_ACCEL", get_SDL_SENSOR_ACCEL, null);
			L.RegVar("SDL_SENSOR_GYRO", get_SDL_SENSOR_GYRO, null);
			L.RegVar("SDL_SENSOR_INVALID", get_SDL_SENSOR_INVALID, null);
			L.EndEnum();
        }
        
        private static int get_SDL_SENSOR_UNKNOWN(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_SensorType.SDL_SENSOR_UNKNOWN);
			return 1;
        }
        
        private static int get_SDL_SENSOR_ACCEL(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_SensorType.SDL_SENSOR_ACCEL);
			return 1;
        }
        
        private static int get_SDL_SENSOR_GYRO(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_SensorType.SDL_SENSOR_GYRO);
			return 1;
        }
        
        private static int get_SDL_SENSOR_INVALID(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_SensorType.SDL_SENSOR_INVALID);
			return 1;
        }
    }
}
