//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniToLua
{
    using SDL2;
    
    
    public class SDL21SDL_mixer1Mix_MusicTypeWrap
    {
        
        public static void Register(UniLua.ILuaState L)
        {
			L.BeginEnum(typeof(SDL2.SDL_mixer.Mix_MusicType));
			L.RegVar("MUS_NONE", get_MUS_NONE, null);
			L.RegVar("MUS_CMD", get_MUS_CMD, null);
			L.RegVar("MUS_WAV", get_MUS_WAV, null);
			L.RegVar("MUS_MOD", get_MUS_MOD, null);
			L.RegVar("MUS_MID", get_MUS_MID, null);
			L.RegVar("MUS_OGG", get_MUS_OGG, null);
			L.RegVar("MUS_MP3", get_MUS_MP3, null);
			L.RegVar("MUS_MP3_MAD_UNUSED", get_MUS_MP3_MAD_UNUSED, null);
			L.RegVar("MUS_FLAC", get_MUS_FLAC, null);
			L.RegVar("MUS_MODPLUG_UNUSED", get_MUS_MODPLUG_UNUSED, null);
			L.RegVar("MUS_OPUS", get_MUS_OPUS, null);
			L.EndEnum();
        }
        
        private static int get_MUS_NONE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL_mixer.Mix_MusicType.MUS_NONE);
			return 1;
        }
        
        private static int get_MUS_CMD(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL_mixer.Mix_MusicType.MUS_CMD);
			return 1;
        }
        
        private static int get_MUS_WAV(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL_mixer.Mix_MusicType.MUS_WAV);
			return 1;
        }
        
        private static int get_MUS_MOD(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL_mixer.Mix_MusicType.MUS_MOD);
			return 1;
        }
        
        private static int get_MUS_MID(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL_mixer.Mix_MusicType.MUS_MID);
			return 1;
        }
        
        private static int get_MUS_OGG(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL_mixer.Mix_MusicType.MUS_OGG);
			return 1;
        }
        
        private static int get_MUS_MP3(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL_mixer.Mix_MusicType.MUS_MP3);
			return 1;
        }
        
        private static int get_MUS_MP3_MAD_UNUSED(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL_mixer.Mix_MusicType.MUS_MP3_MAD_UNUSED);
			return 1;
        }
        
        private static int get_MUS_FLAC(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL_mixer.Mix_MusicType.MUS_FLAC);
			return 1;
        }
        
        private static int get_MUS_MODPLUG_UNUSED(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL_mixer.Mix_MusicType.MUS_MODPLUG_UNUSED);
			return 1;
        }
        
        private static int get_MUS_OPUS(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL_mixer.Mix_MusicType.MUS_OPUS);
			return 1;
        }
    }
}
