//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniToLua
{
    using SDL2;
    using System;
    
    
    public class SDL21SDL1SDL_WindowEventWrap
    {
        
        public static void Register(UniLua.ILuaState L)
        {
			L.BeginClass(typeof(SDL2.SDL.SDL_WindowEvent), typeof(System.ValueType));
			L.RegFunction("New", _CreateSDL21SDL1SDL_WindowEvent);
			L.RegVar("type", get_type, set_type);
			L.RegVar("timestamp", get_timestamp, set_timestamp);
			L.RegVar("windowID", get_windowID, set_windowID);
			L.RegVar("windowEvent", get_windowEvent, set_windowEvent);
			L.RegVar("data1", get_data1, set_data1);
			L.RegVar("data2", get_data2, set_data2);
			L.RegFunction("Equals", Equals);
			L.RegFunction("GetHashCode", GetHashCode);
			L.RegFunction("ToString", ToString);
			L.RegFunction("GetType", GetType);
			L.EndClass();
        }
        
        private static int _CreateSDL21SDL1SDL_WindowEvent(UniLua.ILuaState L)
        {
			if(L.CheckNum(0)) {
				L.PushAny<SDL2.SDL.SDL_WindowEvent>(default(SDL2.SDL.SDL_WindowEvent));
				return 1;
			}
			L.L_Error("call SDL_WindowEvent constructor args is error");
			return 1;
        }
        
        private static int get_type(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.SDL_WindowEvent) L.ToUserData(1);
			L.PushAny<SDL2.SDL.SDL_EventType>(obj.type);
			return 1;
        }
        
        private static int set_type(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.SDL_WindowEvent) L.ToUserData(1);
			var value = L.CheckAny<SDL2.SDL.SDL_EventType>(2);
			obj.type = value;
			return 0;
        }
        
        private static int get_timestamp(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.SDL_WindowEvent) L.ToUserData(1);
			L.PushAny<uint>(obj.timestamp);
			return 1;
        }
        
        private static int set_timestamp(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.SDL_WindowEvent) L.ToUserData(1);
			var value = L.CheckAny<uint>(2);
			obj.timestamp = value;
			return 0;
        }
        
        private static int get_windowID(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.SDL_WindowEvent) L.ToUserData(1);
			L.PushAny<uint>(obj.windowID);
			return 1;
        }
        
        private static int set_windowID(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.SDL_WindowEvent) L.ToUserData(1);
			var value = L.CheckAny<uint>(2);
			obj.windowID = value;
			return 0;
        }
        
        private static int get_windowEvent(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.SDL_WindowEvent) L.ToUserData(1);
			L.PushAny<SDL2.SDL.SDL_WindowEventID>(obj.windowEvent);
			return 1;
        }
        
        private static int set_windowEvent(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.SDL_WindowEvent) L.ToUserData(1);
			var value = L.CheckAny<SDL2.SDL.SDL_WindowEventID>(2);
			obj.windowEvent = value;
			return 0;
        }
        
        private static int get_data1(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.SDL_WindowEvent) L.ToUserData(1);
			L.PushAny<int>(obj.data1);
			return 1;
        }
        
        private static int set_data1(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.SDL_WindowEvent) L.ToUserData(1);
			var value = L.CheckAny<int>(2);
			obj.data1 = value;
			return 0;
        }
        
        private static int get_data2(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.SDL_WindowEvent) L.ToUserData(1);
			L.PushAny<int>(obj.data2);
			return 1;
        }
        
        private static int set_data2(UniLua.ILuaState L)
        {
			var obj = (SDL2.SDL.SDL_WindowEvent) L.ToUserData(1);
			var value = L.CheckAny<int>(2);
			obj.data2 = value;
			return 0;
        }
        
        private static int Equals(UniLua.ILuaState L)
        {
			if(L.CheckNum(2) && L.CheckType<SDL2.SDL.SDL_WindowEvent, object>(1))
			{
				bool result;
				var obj = (SDL2.SDL.SDL_WindowEvent) L.ToUserData(1);
				var arg1 = L.CheckAny<object>(2);
				result = obj.Equals(arg1);
				L.PushAny<bool>(result);
				return 1;
			}
			L.L_Error("call function Equals args is error");
			return 1;
        }
        
        private static int GetHashCode(UniLua.ILuaState L)
        {
			if(L.CheckNum(1))
			{
				int result;
				var obj = (SDL2.SDL.SDL_WindowEvent) L.ToUserData(1);
				result = obj.GetHashCode();
				L.PushAny<int>(result);
				return 1;
			}
			L.L_Error("call function GetHashCode args is error");
			return 1;
        }
        
        private static int ToString(UniLua.ILuaState L)
        {
			if(L.CheckNum(1))
			{
				string result;
				var obj = (SDL2.SDL.SDL_WindowEvent) L.ToUserData(1);
				result = obj.ToString();
				L.PushAny<string>(result);
				return 1;
			}
			L.L_Error("call function ToString args is error");
			return 1;
        }
        
        private static int GetType(UniLua.ILuaState L)
        {
			if(L.CheckNum(1))
			{
				System.Type result;
				var obj = (SDL2.SDL.SDL_WindowEvent) L.ToUserData(1);
				result = obj.GetType();
				L.PushAny<System.Type>(result);
				return 1;
			}
			L.L_Error("call function GetType args is error");
			return 1;
        }
    }
}
