//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniToLua
{
    using SDL2;
    
    
    public class SDL21SDL1SDL_WinRT_DeviceFamilyWrap
    {
        
        public static void Register(UniLua.ILuaState L)
        {
			L.BeginEnum(typeof(SDL2.SDL.SDL_WinRT_DeviceFamily));
			L.RegVar("SDL_WINRT_DEVICEFAMILY_UNKNOWN", get_SDL_WINRT_DEVICEFAMILY_UNKNOWN, null);
			L.RegVar("SDL_WINRT_DEVICEFAMILY_DESKTOP", get_SDL_WINRT_DEVICEFAMILY_DESKTOP, null);
			L.RegVar("SDL_WINRT_DEVICEFAMILY_MOBILE", get_SDL_WINRT_DEVICEFAMILY_MOBILE, null);
			L.RegVar("SDL_WINRT_DEVICEFAMILY_XBOX", get_SDL_WINRT_DEVICEFAMILY_XBOX, null);
			L.EndEnum();
        }
        
        private static int get_SDL_WINRT_DEVICEFAMILY_UNKNOWN(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_WinRT_DeviceFamily.SDL_WINRT_DEVICEFAMILY_UNKNOWN);
			return 1;
        }
        
        private static int get_SDL_WINRT_DEVICEFAMILY_DESKTOP(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_WinRT_DeviceFamily.SDL_WINRT_DEVICEFAMILY_DESKTOP);
			return 1;
        }
        
        private static int get_SDL_WINRT_DEVICEFAMILY_MOBILE(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_WinRT_DeviceFamily.SDL_WINRT_DEVICEFAMILY_MOBILE);
			return 1;
        }
        
        private static int get_SDL_WINRT_DEVICEFAMILY_XBOX(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_WinRT_DeviceFamily.SDL_WINRT_DEVICEFAMILY_XBOX);
			return 1;
        }
    }
}
