//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniToLua
{
    using SDL2;
    
    
    public class SDL21SDL1SDL_MessageBoxColorTypeWrap
    {
        
        public static void Register(UniLua.ILuaState L)
        {
			L.BeginEnum(typeof(SDL2.SDL.SDL_MessageBoxColorType));
			L.RegVar("SDL_MESSAGEBOX_COLOR_BACKGROUND", get_SDL_MESSAGEBOX_COLOR_BACKGROUND, null);
			L.RegVar("SDL_MESSAGEBOX_COLOR_TEXT", get_SDL_MESSAGEBOX_COLOR_TEXT, null);
			L.RegVar("SDL_MESSAGEBOX_COLOR_BUTTON_BORDER", get_SDL_MESSAGEBOX_COLOR_BUTTON_BORDER, null);
			L.RegVar("SDL_MESSAGEBOX_COLOR_BUTTON_BACKGROUND", get_SDL_MESSAGEBOX_COLOR_BUTTON_BACKGROUND, null);
			L.RegVar("SDL_MESSAGEBOX_COLOR_BUTTON_SELECTED", get_SDL_MESSAGEBOX_COLOR_BUTTON_SELECTED, null);
			L.RegVar("SDL_MESSAGEBOX_COLOR_MAX", get_SDL_MESSAGEBOX_COLOR_MAX, null);
			L.EndEnum();
        }
        
        private static int get_SDL_MESSAGEBOX_COLOR_BACKGROUND(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_MessageBoxColorType.SDL_MESSAGEBOX_COLOR_BACKGROUND);
			return 1;
        }
        
        private static int get_SDL_MESSAGEBOX_COLOR_TEXT(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_MessageBoxColorType.SDL_MESSAGEBOX_COLOR_TEXT);
			return 1;
        }
        
        private static int get_SDL_MESSAGEBOX_COLOR_BUTTON_BORDER(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_MessageBoxColorType.SDL_MESSAGEBOX_COLOR_BUTTON_BORDER);
			return 1;
        }
        
        private static int get_SDL_MESSAGEBOX_COLOR_BUTTON_BACKGROUND(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_MessageBoxColorType.SDL_MESSAGEBOX_COLOR_BUTTON_BACKGROUND);
			return 1;
        }
        
        private static int get_SDL_MESSAGEBOX_COLOR_BUTTON_SELECTED(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_MessageBoxColorType.SDL_MESSAGEBOX_COLOR_BUTTON_SELECTED);
			return 1;
        }
        
        private static int get_SDL_MESSAGEBOX_COLOR_MAX(UniLua.ILuaState L)
        {
			L.PushLightUserData(SDL2.SDL.SDL_MessageBoxColorType.SDL_MESSAGEBOX_COLOR_MAX);
			return 1;
        }
    }
}
