//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniToLua
{
    using SoftwareRenderer.Materials;
    using MathLib;
    using System;
    
    
    public class SoftwareRenderer1Materials1LightMaterialWrap
    {
        
        public static void Register(UniLua.ILuaState L)
        {
			L.BeginClass(typeof(SoftwareRenderer.Materials.LightMaterial), null);
			L.RegFunction("New", _CreateSoftwareRenderer1Materials1LightMaterial);
			L.RegVar("color", get_color, set_color);
			L.RegFunction("GetType", GetType);
			L.RegFunction("ToString", ToString);
			L.RegFunction("Equals", Equals);
			L.RegFunction("GetHashCode", GetHashCode);
			L.EndClass();
        }
        
        private static int _CreateSoftwareRenderer1Materials1LightMaterial(UniLua.ILuaState L)
        {
			if(L.CheckNum(0))
			{
				L.PushAny<SoftwareRenderer.Materials.LightMaterial>(new SoftwareRenderer.Materials.LightMaterial());
				return 1;
			}
			L.L_Error("call LightMaterial constructor args is error");
			return 1;
        }
        
        private static int get_color(UniLua.ILuaState L)
        {
			var obj = (SoftwareRenderer.Materials.LightMaterial) L.ToUserData(1);
			L.PushAny<MathLib.Color>(obj.color);
			return 1;
        }
        
        private static int set_color(UniLua.ILuaState L)
        {
			var obj = (SoftwareRenderer.Materials.LightMaterial) L.ToUserData(1);
			var value = L.CheckAny<MathLib.Color>(2);
			obj.color = value;
			return 0;
        }
        
        private static int GetType(UniLua.ILuaState L)
        {
			if(L.CheckNum(1))
			{
				System.Type result;
				var obj = (SoftwareRenderer.Materials.LightMaterial) L.ToUserData(1);
				result = obj.GetType();
				L.PushAny<System.Type>(result);
				return 1;
			}
			L.L_Error("call function GetType args is error");
			return 1;
        }
        
        private static int ToString(UniLua.ILuaState L)
        {
			if(L.CheckNum(1))
			{
				string result;
				var obj = (SoftwareRenderer.Materials.LightMaterial) L.ToUserData(1);
				result = obj.ToString();
				L.PushAny<string>(result);
				return 1;
			}
			L.L_Error("call function ToString args is error");
			return 1;
        }
        
        private static int Equals(UniLua.ILuaState L)
        {
			if(L.CheckNum(2) && L.CheckType<SoftwareRenderer.Materials.LightMaterial, object>(1))
			{
				bool result;
				var obj = (SoftwareRenderer.Materials.LightMaterial) L.ToUserData(1);
				var arg1 = L.CheckAny<object>(2);
				result = obj.Equals(arg1);
				L.PushAny<bool>(result);
				return 1;
			}
			L.L_Error("call function Equals args is error");
			return 1;
        }
        
        private static int GetHashCode(UniLua.ILuaState L)
        {
			if(L.CheckNum(1))
			{
				int result;
				var obj = (SoftwareRenderer.Materials.LightMaterial) L.ToUserData(1);
				result = obj.GetHashCode();
				L.PushAny<int>(result);
				return 1;
			}
			L.L_Error("call function GetHashCode args is error");
			return 1;
        }
    }
}
