//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniToLua
{
    using SoftwareRenderer.Render;
    
    
    public class SoftwareRenderer1Render1TextureFilterModeWrap
    {
        
        public static void Register(UniLua.ILuaState L)
        {
			L.BeginEnum(typeof(SoftwareRenderer.Render.TextureFilterMode));
			L.RegVar("Point", get_Point, null);
			L.RegVar("Bilinear", get_Bilinear, null);
			L.EndEnum();
        }
        
        private static int get_Point(UniLua.ILuaState L)
        {
			L.PushLightUserData(SoftwareRenderer.Render.TextureFilterMode.Point);
			return 1;
        }
        
        private static int get_Bilinear(UniLua.ILuaState L)
        {
			L.PushLightUserData(SoftwareRenderer.Render.TextureFilterMode.Bilinear);
			return 1;
        }
    }
}
